package.path=assert(os.getenv('PW_FEATURE_LIB'))..'/?.lua;'..package.path
local F,S,U,X,tap,hook,controller,action,exitBattle=require('bw_helpers')('BWFlows')
local function finish()
 for i=1,500 do if F.ow() then return true end;tap('B',1,20) end
 F.shot('return_timeout');return false
end
F.run(function()
 assert(F.boot(100));hook(0);hook(4,0,300);hook(16);hook(12);hook(1,0,600);assert(action())
 F.shot('contest_commands');F.press('R',4);F.idle(540)
 F.check('contest capture returns through field callback',finish());hook(17)
 F.check('contest mode remains active after capture',F.r16(X.gSpecialVar_0x8005)==1)
 F.check('contest capture retains captured mon',F.r16(U.gSpecialVar_0x8006)==2)
 hook(0);hook(1,1,600);assert(action());tap('A');tap('A')
 F.check('double battle enters target selection',controller('HandleInputChooseTarget'))
 local target=F.r8(U.gMultiUsePlayerCursor);tap('Left');F.shot('double_target')
 F.check('target cycling changes target',F.r8(U.gMultiUsePlayerCursor)~=target)
 tap('B');F.check('target cancel returns to moves',controller('HandleInputChooseMove'))
 tap('A');tap('A')
 F.check('second battler command choice',controller('HandleInputChooseAction',2));F.shot('second_commands')
 tap('B');F.idle(120)
 F.check('second action cancellation returns to first battler',controller('HandleInputChooseAction',0))
 tap('A');tap('A');tap('A')
 assert(controller('HandleInputChooseAction',2));tap('A');tap('A');tap('A')
 F.check('double battle completes a real turn',action())
 hook(124,0,1200)
 F.check('recorded double battle saved',F.r16(X.gSpecialVar_0x8005)==1)
 assert(exitBattle());hook(19,0,1);F.idle(180);F.check('recording starts playback',(F.battleFlags()&0x01000000)~=0);F.shot('recorded_intro')
 F.idle(1800);F.check('recorded battle playback returns',F.ow() or finish());F.shot('recorded_return')
 hook(1,0,600);F.check('fresh battle after recording',action());assert(exitBattle());F.finish()
end)
