#ifndef GUARD_CONSTANTS_JOHTO_FLAGS_H
#define GUARD_CONSTANTS_JOHTO_FLAGS_H

#include "constants/region_flags.h"

// Johto story/hide flags (region merge, always-on). These live in the reserved
// Johto flag bank (FLAG_JOHTO_BASE = 0x6000), stored in SaveBlock3.johtoFlags[]
// via GetFlagPointer()'s Johto branch, so they are isolated from Hoenn/Kanto.
// Populated during the Johto port; this header holds the starting-area slice
// (New Bark Town + Route 29 + Cherrygrove City + interiors). Append new Johto
// flags here as later maps are ported.
#define FLAG_JOHTO_SLICE(n)                  (FLAG_JOHTO_BASE + (n))

// --- Hide flags (object-event visibility) ---
#define FLAG_HIDE_SILVER_NEWBARKTOWN         FLAG_JOHTO_SLICE(0x00)
#define FLAG_HIDE_NEWBARKTOWN_LAB_AIDE       FLAG_JOHTO_SLICE(0x01)
#define FLAG_HIDE_CHIKORITABALL              FLAG_JOHTO_SLICE(0x02)
#define FLAG_HIDE_CYNDAQUILBALL              FLAG_JOHTO_SLICE(0x03)
#define FLAG_HIDE_TOTODILEBALL               FLAG_JOHTO_SLICE(0x04)
#define FLAG_HIDE_LAB_POLICEMAN              FLAG_JOHTO_SLICE(0x05)
#define FLAG_HIDE_MOMS_FRIEND                FLAG_JOHTO_SLICE(0x06)
#define FLAG_HIDE_MOMS_FRIEND2               FLAG_JOHTO_SLICE(0x07)
#define FLAG_HIDE_GUIDE_GENT_CHERRYGROVE     FLAG_JOHTO_SLICE(0x08)
#define FLAG_HIDE_SILVER_CHERRYGROVE         FLAG_JOHTO_SLICE(0x09)
#define FLAG_HIDE_CHERRYGROVE_GUIDE_GENT_HOUSE FLAG_JOHTO_SLICE(0x0A)
#define FLAG_HIDE_ROUTE_30_NPCS              FLAG_JOHTO_SLICE(0x0B)
#define FLAG_HIDE_ECRUTEAK_SILVER            FLAG_JOHTO_SLICE(0x0C)
#define FLAG_HIDE_ECRUTEAK_CITY_THEATER_NPCS FLAG_JOHTO_SLICE(0x0D)
#define FLAG_HIDE_ECRUTEAK_CITY_THEATER_KIMONOS FLAG_JOHTO_SLICE(0x0E)
#define FLAG_HIDE_OLIVINE_PORT_OAK           FLAG_JOHTO_SLICE(0x0F)
#define FLAG_HIDE_SSAQUA_1F_GRANDPA          FLAG_JOHTO_SLICE(0x10)

// --- Story progress flags ---
#define FLAG_JOHTO_ADVENTURE_STARTED               FLAG_JOHTO_SLICE(0x20)
#define FLAG_RECEIVED_FIRST_POTION           FLAG_JOHTO_SLICE(0x21)
#define FLAG_RECEIVED_FIRST_BALLS            FLAG_JOHTO_SLICE(0x22)
#define FLAG_SHOWN_ELM_TOGEPI                FLAG_JOHTO_SLICE(0x23)
#define FLAG_MOM_VISITED                     FLAG_JOHTO_SLICE(0x24)
#define FLAG_VISITED_NEWBARK_TOWN            FLAG_JOHTO_SLICE(0x25)
#define FLAG_VISITED_CHERRYGROVE_CITY        FLAG_JOHTO_SLICE(0x26)
#define FLAG_GOT_MYSTICWATER                 FLAG_JOHTO_SLICE(0x27)
#define FLAG_GOT_SILK_SCARF                  FLAG_JOHTO_SLICE(0x28)
#define FLAG_COMPLETED_HOOH_PUZZLE           FLAG_JOHTO_SLICE(0x29)
#define FLAG_COMPLETED_AERODACTYL_PUZZLE     FLAG_JOHTO_SLICE(0x2A)
#define FLAG_COMPLETED_KABUTO_PUZZLE         FLAG_JOHTO_SLICE(0x2B)
#define FLAG_COMPLETED_OMANYTE_PUZZLE        FLAG_JOHTO_SLICE(0x2C)

// --- Encounter / item / misc flags used by slice maps ---
#define FLAG_DAY_POKEMON                     FLAG_JOHTO_SLICE(0x40)
#define FLAG_NIGHT_POKEMON                   FLAG_JOHTO_SLICE(0x41)
#define FLAG_ITEM_ROUTE_29_POTION            FLAG_JOHTO_SLICE(0x42)

// HnS feature toggle: Exp Share global on/off (story sets it during the lab event).
// Slice maps it into the Johto bank; a later pass can promote it to a global toggle.
#define FLAG_EXP_SHARE                       FLAG_JOHTO_SLICE(0x43)

// === Violet City area (Route 31/32, Ruins of Alph, Sprout Tower, Violet City) ===
// --- Hide flags ---
#define FLAG_HIDE_JOHTO_GYM_LEADERS          FLAG_JOHTO_SLICE(0x11)
#define FLAG_HIDE_SPROUT_TOWER_SILVER        FLAG_JOHTO_SLICE(0x12)
#define FLAG_HIDE_SUDOWOODO                  FLAG_JOHTO_SLICE(0x13)
#define FLAG_HIDE_TRAINER_SCHOOL_EARL        FLAG_JOHTO_SLICE(0x14)
#define FLAG_HIDE_UNION_CAVE_LAPRAS          FLAG_JOHTO_SLICE(0x15)
#define FLAG_HIDE_VIOLET_CITY_AIDE           FLAG_JOHTO_SLICE(0x16)
#define FLAG_HIDE_VIOLET_CITY_EARL           FLAG_JOHTO_SLICE(0x17)
#define FLAG_HIDE_VIOLET_CITY_KIMONO_GIRL    FLAG_JOHTO_SLICE(0x18)

// --- Story progress flags ---
#define FLAG_DEFEATED_VIOLET_GYM             FLAG_JOHTO_SLICE(0x2D)
#define FLAG_VISITED_VIOLET_CITY             FLAG_JOHTO_SLICE(0x2E)
#define FLAG_RECEIVED_TOGEPI_EGG             FLAG_JOHTO_SLICE(0x2F)
#define FLAG_VIOLET_NPC_TRADE_COMPLETED      FLAG_JOHTO_SLICE(0x30)
#define FLAG_AERODACTYL_BROUGHT              FLAG_JOHTO_SLICE(0x31)
#define FLAG_HOOH_BROUGHT                    FLAG_JOHTO_SLICE(0x32)
#define FLAG_KABUTO_BROUGHT                  FLAG_JOHTO_SLICE(0x33)
#define FLAG_OMANYTE_BROUGHT                 FLAG_JOHTO_SLICE(0x34)
#define FLAG_GOT_BLACK_GLASSES               FLAG_JOHTO_SLICE(0x35)
#define FLAG_GOT_HARD_STONE                  FLAG_JOHTO_SLICE(0x36)
#define FLAG_GOT_POISON_BARB                 FLAG_JOHTO_SLICE(0x37)

// --- Ground-item pickup flags (FLAG_ITEM_*) ---
#define FLAG_ITEM_ROUTE_31_ANTIDOE           FLAG_JOHTO_SLICE(0x50)
#define FLAG_ITEM_ROUTE_31_POKEBALL          FLAG_JOHTO_SLICE(0x51)
#define FLAG_ITEM_ROUTE_32_GREATBALL         FLAG_JOHTO_SLICE(0x52)
#define FLAG_ITEM_ROUTE_32_GREATBALL2        FLAG_JOHTO_SLICE(0x53)
#define FLAG_ITEM_ROUTE_32_POTION            FLAG_JOHTO_SLICE(0x54)
#define FLAG_ITEM_ROUTE_32_SUPERPOTION       FLAG_JOHTO_SLICE(0x55)
#define FLAG_ITEM_RUINSOFALPH_CHARCOAL       FLAG_JOHTO_SLICE(0x56)
#define FLAG_ITEM_RUINSOFALPH_ENERGY_POWDER  FLAG_JOHTO_SLICE(0x57)
#define FLAG_ITEM_RUINSOFALPH_ENERGY_ROOT    FLAG_JOHTO_SLICE(0x58)
#define FLAG_ITEM_RUINSOFALPH_HEAL_POWDER_1  FLAG_JOHTO_SLICE(0x59)
#define FLAG_ITEM_RUINSOFALPH_HEAL_POWDER_2  FLAG_JOHTO_SLICE(0x5A)
#define FLAG_ITEM_RUINSOFALPH_LUM_BERRY_1    FLAG_JOHTO_SLICE(0x5B)
#define FLAG_ITEM_RUINSOFALPH_LUM_BERRY_2    FLAG_JOHTO_SLICE(0x5C)
#define FLAG_ITEM_RUINSOFALPH_MAX_REVIVE_1   FLAG_JOHTO_SLICE(0x5D)
#define FLAG_ITEM_RUINSOFALPH_MOON_STONE     FLAG_JOHTO_SLICE(0x5E)
#define FLAG_ITEM_RUINSOFALPH_ORAN_BERRY     FLAG_JOHTO_SLICE(0x5F)
#define FLAG_ITEM_RUINSOFALPH_PECHA_BERRY    FLAG_JOHTO_SLICE(0x60)
#define FLAG_ITEM_RUINSOFALPH_SACRED_ASH     FLAG_JOHTO_SLICE(0x61)
#define FLAG_ITEM_RUINSOFALPH_SITRUS_BERRY_2 FLAG_JOHTO_SLICE(0x62)
#define FLAG_ITEM_RUINSOFALPH_STARDUST       FLAG_JOHTO_SLICE(0x63)
#define FLAG_ITEM_RUINSOFALPH_STAR_PIECE     FLAG_JOHTO_SLICE(0x64)
#define FLAG_ITEM_RUINSOFALPH_WATER_STONE    FLAG_JOHTO_SLICE(0x65)
#define FLAG_ITEM_SPROUT_TOWER_ESCAPE_ROPE   FLAG_JOHTO_SLICE(0x66)
#define FLAG_ITEM_SPROUT_TOWER_PARALYZE_HEAL FLAG_JOHTO_SLICE(0x67)
#define FLAG_ITEM_SPROUT_TOWER_POTION        FLAG_JOHTO_SLICE(0x68)
#define FLAG_ITEM_SPROUT_TOWER_X_DEFEND      FLAG_JOHTO_SLICE(0x69)
#define FLAG_ITEM_VIOLET_CITY_HYPER_POTION   FLAG_JOHTO_SLICE(0x6A)
#define FLAG_ITEM_VIOLET_CITY_PECHA_BERRY    FLAG_JOHTO_SLICE(0x6B)
#define FLAG_ITEM_VIOLET_CITY_RARE_CANDY     FLAG_JOHTO_SLICE(0x6C)
#define FLAG_ITEM_DOME_FOSSIL                FLAG_JOHTO_SLICE(0x6D)
#define FLAG_ITEM_HELIX_FOSSIL               FLAG_JOHTO_SLICE(0x6E)
#define FLAG_ITEM_OLD_AMBER                  FLAG_JOHTO_SLICE(0x6F)
#define FLAG_ITEM_GS_BALL                    FLAG_JOHTO_SLICE(0x70)

#endif // GUARD_CONSTANTS_JOHTO_FLAGS_H
