#ifndef GUARD_CONSTANTS_OPPONENTS_FRLG_H
#define GUARD_CONSTANTS_OPPONENTS_FRLG_H

#include "constants/battle_partner.h"

// Region merge (E5-1): under ALL_REGIONS the Kanto (FRLG) trainers are resident in
// gTrainers[] at a dedicated id block directly after Johto (ids 1097..TRAINERS_COUNT-1 = 1726), so every
// native FRLG id below is rebased by KANTO_TRAINER_ID_OFFSET. Their defeat flags do NOT
// use the inline TRAINER_FLAGS_START window (frozen at TRAINERS_COUNT_HOENN_JOHTO so
// SaveBlock1's flag layout never shifts) - they live in SaveBlock3.kantoTrainerFlags,
// mapped by TrainerIdToDefeatFlag() (battle_setup.c). Guarded by STATIC_ASSERTs in
// src/data.c and src/battle_setup.c.
#if ALL_REGIONS
#define KANTO_TRAINER_ID_OFFSET 1096 // == TRAINERS_COUNT_HOENN_JOHTO (opponents.h)
#else
#define KANTO_TRAINER_ID_OFFSET 0    // FRLG/vanilla builds keep the native ids
#endif

#define TRAINER_NONE                               0
// Literal ids per build config: cpp expansion of an expression emits
// "(1096 +N)" whose internal space breaks GAS macro-argument splitting
// in .include'd map scripts (same reason the Johto block uses literals).
#if ALL_REGIONS
#define TRAINER_YOUNGSTER_BEN                   1097
#define TRAINER_YOUNGSTER_CALVIN                1098
#define TRAINER_YOUNGSTER_JOSH                  1099
#define TRAINER_YOUNGSTER_TIMMY                 1100
#define TRAINER_YOUNGSTER_JOEY                  1101
#define TRAINER_YOUNGSTER_DAN                   1102
#define TRAINER_YOUNGSTER_CHAD                  1103
#define TRAINER_YOUNGSTER_TYLER                 1104
#define TRAINER_YOUNGSTER_EDDIE                 1105
#define TRAINER_YOUNGSTER_DILLON                1106
#define TRAINER_YOUNGSTER_YASU                  1107
#define TRAINER_YOUNGSTER_DAVE                  1108
#define TRAINER_YOUNGSTER_BEN_2                 1109
#define TRAINER_BUG_CATCHER_RICK                1110
#define TRAINER_BUG_CATCHER_DOUG                1111
#define TRAINER_BUG_CATCHER_SAMMY               1112
#define TRAINER_BUG_CATCHER_COLTON              1113
#define TRAINER_BUG_CATCHER_GREG                1114
#define TRAINER_BUG_CATCHER_JAMES               1115
#define TRAINER_BUG_CATCHER_KENT                1116
#define TRAINER_BUG_CATCHER_ROBBY               1117
#define TRAINER_BUG_CATCHER_CALE                1118
#define TRAINER_BUG_CATCHER_KEIGO               1119
#define TRAINER_BUG_CATCHER_ELIJAH              1120
#define TRAINER_BUG_CATCHER_BRENT               1121
#define TRAINER_BUG_CATCHER_CONNER              1122
#define TRAINER_LASS_JANICE                     1123
#define TRAINER_LASS_SALLY                      1124
#define TRAINER_LASS_ROBIN                      1125
#define TRAINER_LASS_CRISSY                     1126
#define TRAINER_LASS_MIRIAM                     1127
#define TRAINER_LASS_IRIS                       1128
#define TRAINER_LASS_RELI                       1129
#define TRAINER_LASS_ALI                        1130
#define TRAINER_LASS_HALEY                      1131
#define TRAINER_LASS_ANN                        1132
#define TRAINER_LASS_DAWN                       1133
#define TRAINER_LASS_PAIGE                      1134
#define TRAINER_LASS_ANDREA                     1135
#define TRAINER_LASS_MEGAN                      1136
#define TRAINER_LASS_JULIA                      1137
#define TRAINER_LASS_KAY                        1138
#define TRAINER_LASS_LISA                       1139
#define TRAINER_SAILOR_EDMOND                   1140
#define TRAINER_SAILOR_TREVOR                   1141
#define TRAINER_SAILOR_LEONARD                  1142
#define TRAINER_SAILOR_DUNCAN                   1143
#define TRAINER_SAILOR_HUEY                     1144
#define TRAINER_SAILOR_DYLAN                    1145
#define TRAINER_SAILOR_PHILLIP                  1146
#define TRAINER_SAILOR_DWAYNE                   1147
#define TRAINER_CAMPER_LIAM                     1148
#define TRAINER_CAMPER_SHANE                    1149
#define TRAINER_CAMPER_ETHAN                    1150
#define TRAINER_CAMPER_RICKY                    1151
#define TRAINER_CAMPER_JEFF                     1152
#define TRAINER_CAMPER_CHRIS                    1153
#define TRAINER_CAMPER_DREW                     1154
#define TRAINER_PICNICKER_DIANA                 1155
#define TRAINER_PICNICKER_NANCY                 1156
#define TRAINER_PICNICKER_ISABELLE              1157
#define TRAINER_PICNICKER_KELSEY                1158
#define TRAINER_PICNICKER_ALICIA                1159
#define TRAINER_PICNICKER_CAITLIN               1160
#define TRAINER_PICNICKER_HEIDI                 1161
#define TRAINER_PICNICKER_CAROL                 1162
#define TRAINER_PICNICKER_SOFIA                 1163
#define TRAINER_PICNICKER_MARTHA                1164
#define TRAINER_PICNICKER_TINA                  1165
#define TRAINER_PICNICKER_HANNAH                1166
#define TRAINER_POKEMANIAC_MARK                 1167
#define TRAINER_POKEMANIAC_HERMAN               1168
#define TRAINER_POKEMANIAC_COOPER               1169
#define TRAINER_POKEMANIAC_STEVE                1170
#define TRAINER_POKEMANIAC_WINSTON              1171
#define TRAINER_POKEMANIAC_DAWSON               1172
#define TRAINER_POKEMANIAC_ASHTON               1173
#define TRAINER_SUPER_NERD_JOVAN                1174
#define TRAINER_SUPER_NERD_MIGUEL               1175
#define TRAINER_SUPER_NERD_AIDAN                1176
#define TRAINER_SUPER_NERD_GLENN                1177
#define TRAINER_SUPER_NERD_LESLIE               1178
#define TRAINER_SUPER_NERD_ERIK                 1179
#define TRAINER_SUPER_NERD_AVERY                1180
#define TRAINER_SUPER_NERD_DEREK                1181
#define TRAINER_SUPER_NERD_ZAC                  1182
#define TRAINER_HIKER_MARCOS                    1183
#define TRAINER_HIKER_FRANKLIN                  1184
#define TRAINER_HIKER_NOB                       1185
#define TRAINER_HIKER_WAYNE                     1186
#define TRAINER_HIKER_ALAN                      1187
#define TRAINER_HIKER_BRICE                     1188
#define TRAINER_HIKER_CLARK                     1189
#define TRAINER_HIKER_TRENT                     1190
#define TRAINER_HIKER_DUDLEY                    1191
#define TRAINER_HIKER_ALLEN                     1192
#define TRAINER_HIKER_ERIC                      1193
#define TRAINER_HIKER_LENNY                     1194
#define TRAINER_HIKER_OLIVER                    1195
#define TRAINER_HIKER_LUCAS                     1196
#define TRAINER_BIKER_JARED                     1197
#define TRAINER_BIKER_MALIK                     1198
#define TRAINER_BIKER_ERNEST                    1199
#define TRAINER_BIKER_ALEX                      1200
#define TRAINER_BIKER_LAO                       1201
#define TRAINER_BIKER_HIDEO                     1202
#define TRAINER_BIKER_RUBEN                     1203
#define TRAINER_BIKER_BILLY                     1204
#define TRAINER_BIKER_NIKOLAS                   1205
#define TRAINER_BIKER_JAXON                     1206
#define TRAINER_BIKER_WILLIAM                   1207
#define TRAINER_BIKER_LUKAS                     1208
#define TRAINER_BIKER_ISAAC                     1209
#define TRAINER_BIKER_GERALD                    1210
#define TRAINER_BURGLAR_QUINN                   1211
#define TRAINER_BURGLAR_RAMON                   1212
#define TRAINER_BURGLAR_DUSTY                   1213
#define TRAINER_BURGLAR_ARNIE                   1214
#define TRAINER_BURGLAR_SIMON                   1215
#define TRAINER_BURGLAR_LEWIS                   1216
#define TRAINER_ENGINEER_BAILY                  1217
#define TRAINER_ENGINEER_BRAXTON                1218
#define TRAINER_ENGINEER_BERNIE                 1219
#define TRAINER_FISHERMAN_DALE                  1220
#define TRAINER_FISHERMAN_BARNY                 1221
#define TRAINER_FISHERMAN_NED                   1222
#define TRAINER_FISHERMAN_CHIP                  1223
#define TRAINER_FISHERMAN_HANK                  1224
#define TRAINER_FISHERMAN_ELLIOT                1225
#define TRAINER_FISHERMAN_RONALD                1226
#define TRAINER_FISHERMAN_CLAUDE                1227
#define TRAINER_FISHERMAN_WADE                  1228
#define TRAINER_FISHERMAN_NOLAN                 1229
#define TRAINER_FISHERMAN_ANDREW                1230
#define TRAINER_SWIMMER_MALE_LUIS               1231
#define TRAINER_SWIMMER_MALE_RICHARD            1232
#define TRAINER_SWIMMER_MALE_REECE              1233
#define TRAINER_SWIMMER_MALE_MATTHEW            1234
#define TRAINER_SWIMMER_MALE_DOUGLAS            1235
#define TRAINER_SWIMMER_MALE_DAVID              1236
#define TRAINER_SWIMMER_MALE_TONY               1237
#define TRAINER_SWIMMER_MALE_AXLE               1238
#define TRAINER_SWIMMER_MALE_BARRY              1239
#define TRAINER_SWIMMER_MALE_DEAN               1240
#define TRAINER_SWIMMER_MALE_DARRIN             1241
#define TRAINER_SWIMMER_MALE_SPENCER            1242
#define TRAINER_SWIMMER_MALE_JACK               1243
#define TRAINER_SWIMMER_MALE_JEROME             1244
#define TRAINER_SWIMMER_MALE_ROLAND             1245
#define TRAINER_CUE_BALL_KOJI                   1246
#define TRAINER_CUE_BALL_LUKE                   1247
#define TRAINER_CUE_BALL_CAMRON                 1248
#define TRAINER_CUE_BALL_RAUL                   1249
#define TRAINER_CUE_BALL_ISAIAH                 1250
#define TRAINER_CUE_BALL_ZEEK                   1251
#define TRAINER_CUE_BALL_JAMAL                  1252
#define TRAINER_CUE_BALL_COREY                  1253
#define TRAINER_CUE_BALL_CHASE                  1254
#define TRAINER_GAMER_HUGO                      1255
#define TRAINER_GAMER_JASPER                    1256
#define TRAINER_GAMER_DIRK                      1257
#define TRAINER_GAMER_DARIAN                    1258
#define TRAINER_GAMER_STAN                      1259
#define TRAINER_GAMER_RICH                      1260
#define TRAINER_BEAUTY_BRIDGET                  1261
#define TRAINER_BEAUTY_TAMIA                    1262
#define TRAINER_BEAUTY_LORI                     1263
#define TRAINER_BEAUTY_LOLA                     1264
#define TRAINER_BEAUTY_SHEILA                   1265
#define TRAINER_SWIMMER_FEMALE_TIFFANY          1266
#define TRAINER_SWIMMER_FEMALE_NORA             1267
#define TRAINER_SWIMMER_FEMALE_MELISSA          1268
#define TRAINER_BEAUTY_GRACE                    1269
#define TRAINER_BEAUTY_OLIVIA                   1270
#define TRAINER_BEAUTY_LAUREN                   1271
#define TRAINER_SWIMMER_FEMALE_ANYA             1272
#define TRAINER_SWIMMER_FEMALE_ALICE            1273
#define TRAINER_SWIMMER_FEMALE_CONNIE           1274
#define TRAINER_SWIMMER_FEMALE_SHIRLEY          1275
#define TRAINER_PSYCHIC_JOHAN                   1276
#define TRAINER_PSYCHIC_TYRON                   1277
#define TRAINER_PSYCHIC_CAMERON                 1278
#define TRAINER_PSYCHIC_PRESTON                 1279
#define TRAINER_ROCKER_RANDALL                  1280
#define TRAINER_ROCKER_LUCA                     1281
#define TRAINER_JUGGLER_DALTON                  1282
#define TRAINER_JUGGLER_NELSON                  1283
#define TRAINER_JUGGLER_KIRK                    1284
#define TRAINER_JUGGLER_SHAWN                   1285
#define TRAINER_JUGGLER_GREGORY                 1286
#define TRAINER_JUGGLER_EDWARD                  1287
#define TRAINER_JUGGLER_KAYDEN                  1288
#define TRAINER_JUGGLER_NATE                    1289
#define TRAINER_TAMER_PHIL                      1290
#define TRAINER_TAMER_EDGAR                     1291
#define TRAINER_TAMER_JASON                     1292
#define TRAINER_TAMER_COLE                      1293
#define TRAINER_TAMER_VINCENT                   1294
#define TRAINER_TAMER_JOHN                      1295
#define TRAINER_BIRD_KEEPER_SEBASTIAN           1296
#define TRAINER_BIRD_KEEPER_PERRY               1297
#define TRAINER_BIRD_KEEPER_ROBERT              1298
#define TRAINER_BIRD_KEEPER_DONALD              1299
#define TRAINER_BIRD_KEEPER_BENNY               1300
#define TRAINER_BIRD_KEEPER_EDWIN               1301
#define TRAINER_BIRD_KEEPER_CHESTER             1302
#define TRAINER_BIRD_KEEPER_WILTON              1303
#define TRAINER_BIRD_KEEPER_RAMIRO              1304
#define TRAINER_BIRD_KEEPER_JACOB               1305
#define TRAINER_BIRD_KEEPER_ROGER               1306
#define TRAINER_BIRD_KEEPER_REED                1307
#define TRAINER_BIRD_KEEPER_KEITH               1308
#define TRAINER_BIRD_KEEPER_CARTER              1309
#define TRAINER_BIRD_KEEPER_MITCH               1310
#define TRAINER_BIRD_KEEPER_BECK                1311
#define TRAINER_BIRD_KEEPER_MARLON              1312
#define TRAINER_BLACK_BELT_KOICHI               1313
#define TRAINER_BLACK_BELT_MIKE                 1314
#define TRAINER_BLACK_BELT_HIDEKI               1315
#define TRAINER_BLACK_BELT_AARON                1316
#define TRAINER_BLACK_BELT_HITOSHI              1317
#define TRAINER_BLACK_BELT_ATSUSHI              1318
#define TRAINER_BLACK_BELT_KIYO                 1319
#define TRAINER_BLACK_BELT_TAKASHI              1320
#define TRAINER_BLACK_BELT_DAISUKE              1321
#define TRAINER_RIVAL_OAKS_LAB_SQUIRTLE         1322
#define TRAINER_RIVAL_OAKS_LAB_BULBASAUR        1323
#define TRAINER_RIVAL_OAKS_LAB_CHARMANDER       1324
#define TRAINER_RIVAL_ROUTE22_EARLY_SQUIRTLE    1325
#define TRAINER_RIVAL_ROUTE22_EARLY_BULBASAUR   1326
#define TRAINER_RIVAL_ROUTE22_EARLY_CHARMANDER  1327
#define TRAINER_RIVAL_CERULEAN_SQUIRTLE         1328
#define TRAINER_RIVAL_CERULEAN_BULBASAUR        1329
#define TRAINER_RIVAL_CERULEAN_CHARMANDER       1330
#define TRAINER_SCIENTIST_TED                   1331
#define TRAINER_SCIENTIST_CONNOR                1332
#define TRAINER_SCIENTIST_JERRY                 1333
#define TRAINER_SCIENTIST_JOSE                  1334
#define TRAINER_SCIENTIST_RODNEY                1335
#define TRAINER_SCIENTIST_BEAU                  1336
#define TRAINER_SCIENTIST_TAYLOR                1337
#define TRAINER_SCIENTIST_JOSHUA                1338
#define TRAINER_SCIENTIST_PARKER                1339
#define TRAINER_SCIENTIST_ED                    1340
#define TRAINER_SCIENTIST_TRAVIS                1341
#define TRAINER_SCIENTIST_BRAYDON               1342
#define TRAINER_SCIENTIST_IVAN                  1343
#define TRAINER_BOSS_GIOVANNI                   1344
#define TRAINER_BOSS_GIOVANNI_2                 1345
#define TRAINER_LEADER_GIOVANNI                 1346
#define TRAINER_TEAM_ROCKET_GRUNT               1347
#define TRAINER_TEAM_ROCKET_GRUNT_2             1348
#define TRAINER_TEAM_ROCKET_GRUNT_3             1349
#define TRAINER_TEAM_ROCKET_GRUNT_4             1350
#define TRAINER_TEAM_ROCKET_GRUNT_5             1351
#define TRAINER_TEAM_ROCKET_GRUNT_6             1352
#define TRAINER_TEAM_ROCKET_GRUNT_7             1353
#define TRAINER_TEAM_ROCKET_GRUNT_8             1354
#define TRAINER_TEAM_ROCKET_GRUNT_9             1355
#define TRAINER_TEAM_ROCKET_GRUNT_10            1356
#define TRAINER_TEAM_ROCKET_GRUNT_11            1357
#define TRAINER_TEAM_ROCKET_GRUNT_12            1358
#define TRAINER_TEAM_ROCKET_GRUNT_13            1359
#define TRAINER_TEAM_ROCKET_GRUNT_14            1360
#define TRAINER_TEAM_ROCKET_GRUNT_15            1361
#define TRAINER_TEAM_ROCKET_GRUNT_16            1362
#define TRAINER_TEAM_ROCKET_GRUNT_17            1363
#define TRAINER_TEAM_ROCKET_GRUNT_18            1364
#define TRAINER_TEAM_ROCKET_GRUNT_19            1365
#define TRAINER_TEAM_ROCKET_GRUNT_20            1366
#define TRAINER_TEAM_ROCKET_GRUNT_21            1367
#define TRAINER_TEAM_ROCKET_GRUNT_22            1368
#define TRAINER_TEAM_ROCKET_GRUNT_23            1369
#define TRAINER_TEAM_ROCKET_GRUNT_24            1370
#define TRAINER_TEAM_ROCKET_GRUNT_25            1371
#define TRAINER_TEAM_ROCKET_GRUNT_26            1372
#define TRAINER_TEAM_ROCKET_GRUNT_27            1373
#define TRAINER_TEAM_ROCKET_GRUNT_28            1374
#define TRAINER_TEAM_ROCKET_GRUNT_29            1375
#define TRAINER_TEAM_ROCKET_GRUNT_30            1376
#define TRAINER_TEAM_ROCKET_GRUNT_31            1377
#define TRAINER_TEAM_ROCKET_GRUNT_32            1378
#define TRAINER_TEAM_ROCKET_GRUNT_33            1379
#define TRAINER_TEAM_ROCKET_GRUNT_34            1380
#define TRAINER_TEAM_ROCKET_GRUNT_35            1381
#define TRAINER_TEAM_ROCKET_GRUNT_36            1382
#define TRAINER_TEAM_ROCKET_GRUNT_37            1383
#define TRAINER_TEAM_ROCKET_GRUNT_38            1384
#define TRAINER_TEAM_ROCKET_GRUNT_39            1385
#define TRAINER_TEAM_ROCKET_GRUNT_40            1386
#define TRAINER_TEAM_ROCKET_GRUNT_41            1387
#define TRAINER_COOLTRAINER_SAMUEL              1388
#define TRAINER_COOLTRAINER_GEORGE              1389
#define TRAINER_COOLTRAINER_COLBY               1390
#define TRAINER_COOLTRAINER_PAUL                1391
#define TRAINER_COOLTRAINER_ROLANDO             1392
#define TRAINER_COOLTRAINER_GILBERT             1393
#define TRAINER_COOLTRAINER_OWEN                1394
#define TRAINER_COOLTRAINER_BERKE               1395
#define TRAINER_COOLTRAINER_YUJI                1396
#define TRAINER_COOLTRAINER_WARREN              1397
#define TRAINER_COOLTRAINER_MARY                1398
#define TRAINER_COOLTRAINER_CAROLINE            1399
#define TRAINER_COOLTRAINER_ALEXA               1400
#define TRAINER_COOLTRAINER_SHANNON             1401
#define TRAINER_COOLTRAINER_NAOMI               1402
#define TRAINER_COOLTRAINER_BROOKE              1403
#define TRAINER_COOLTRAINER_AUSTINA             1404
#define TRAINER_COOLTRAINER_JULIE               1405
#define TRAINER_ELITE_FOUR_LORELEI              1406
#define TRAINER_ELITE_FOUR_BRUNO                1407
#define TRAINER_ELITE_FOUR_AGATHA               1408
#define TRAINER_ELITE_FOUR_LANCE                1409
#define TRAINER_LEADER_BROCK                    1410
#define TRAINER_LEADER_MISTY                    1411
#define TRAINER_LEADER_LT_SURGE                 1412
#define TRAINER_LEADER_ERIKA                    1413
#define TRAINER_LEADER_KOGA                     1414
#define TRAINER_LEADER_BLAINE                   1415
#define TRAINER_LEADER_SABRINA                  1416
#define TRAINER_GENTLEMAN_THOMAS                1417
#define TRAINER_GENTLEMAN_ARTHUR                1418
#define TRAINER_GENTLEMAN_TUCKER                1419
#define TRAINER_GENTLEMAN_NORTON                1420
#define TRAINER_GENTLEMAN_WALTER                1421
#define TRAINER_RIVAL_SS_ANNE_SQUIRTLE          1422
#define TRAINER_RIVAL_SS_ANNE_BULBASAUR         1423
#define TRAINER_RIVAL_SS_ANNE_CHARMANDER        1424
#define TRAINER_RIVAL_POKEMON_TOWER_SQUIRTLE    1425
#define TRAINER_RIVAL_POKEMON_TOWER_BULBASAUR   1426
#define TRAINER_RIVAL_POKEMON_TOWER_CHARMANDER  1427
#define TRAINER_RIVAL_SILPH_SQUIRTLE            1428
#define TRAINER_RIVAL_SILPH_BULBASAUR           1429
#define TRAINER_RIVAL_SILPH_CHARMANDER          1430
#define TRAINER_RIVAL_ROUTE22_LATE_SQUIRTLE     1431
#define TRAINER_RIVAL_ROUTE22_LATE_BULBASAUR    1432
#define TRAINER_RIVAL_ROUTE22_LATE_CHARMANDER   1433
#define TRAINER_CHAMPION_FIRST_SQUIRTLE         1434
#define TRAINER_CHAMPION_FIRST_BULBASAUR        1435
#define TRAINER_CHAMPION_FIRST_CHARMANDER       1436
#define TRAINER_CHANNELER_PATRICIA              1437
#define TRAINER_CHANNELER_CARLY                 1438
#define TRAINER_CHANNELER_HOPE                  1439
#define TRAINER_CHANNELER_PAULA                 1440
#define TRAINER_CHANNELER_LAUREL                1441
#define TRAINER_CHANNELER_JODY                  1442
#define TRAINER_CHANNELER_TAMMY                 1443
#define TRAINER_CHANNELER_RUTH                  1444
#define TRAINER_CHANNELER_KARINA                1445
#define TRAINER_CHANNELER_JANAE                 1446
#define TRAINER_CHANNELER_ANGELICA              1447
#define TRAINER_CHANNELER_EMILIA                1448
#define TRAINER_CHANNELER_JENNIFER              1449
#define TRAINER_CHANNELER_AMANDA                1450
#define TRAINER_CHANNELER_STACY                 1451
#define TRAINER_CHANNELER_TASHA                 1452
#define TRAINER_HIKER_JEREMY                    1453
#define TRAINER_PICNICKER_ALMA                  1454
#define TRAINER_PICNICKER_SUSIE                 1455
#define TRAINER_PICNICKER_VALERIE               1456
#define TRAINER_PICNICKER_GWEN                  1457
#define TRAINER_BIKER_VIRGIL                    1458
#define TRAINER_CAMPER_FLINT                    1459
#define TRAINER_PICNICKER_MISSY                 1460
#define TRAINER_PICNICKER_IRENE                 1461
#define TRAINER_PICNICKER_DANA                  1462
#define TRAINER_PICNICKER_ARIANA                1463
#define TRAINER_PICNICKER_LEAH                  1464
#define TRAINER_CAMPER_JUSTIN                   1465
#define TRAINER_PICNICKER_YAZMIN                1466
#define TRAINER_PICNICKER_KINDRA                1467
#define TRAINER_PICNICKER_BECKY                 1468
#define TRAINER_PICNICKER_CELIA                 1469
#define TRAINER_GENTLEMAN_BROOKS                1470
#define TRAINER_GENTLEMAN_LAMAR                 1471
#define TRAINER_TWINS_ELI_ANNE                  1472
#define TRAINER_COOL_COUPLE_RAY_TYRA            1473
#define TRAINER_YOUNG_COUPLE_GIA_JES            1474
#define TRAINER_TWINS_KIRI_JAN                  1475
#define TRAINER_CRUSH_KIN_RON_MYA               1476
#define TRAINER_YOUNG_COUPLE_LEA_JED            1477
#define TRAINER_SIS_AND_BRO_LIA_LUC             1478
#define TRAINER_SIS_AND_BRO_LIL_IAN             1479
#define TRAINER_YOUNGSTER_BEN_3                 1480
#define TRAINER_YOUNGSTER_BEN_4                 1481
#define TRAINER_YOUNGSTER_CHAD_2                1482
#define TRAINER_LASS_RELI_2                     1483
#define TRAINER_LASS_RELI_3                     1484
#define TRAINER_YOUNGSTER_TIMMY_2               1485
#define TRAINER_YOUNGSTER_TIMMY_3               1486
#define TRAINER_YOUNGSTER_TIMMY_4               1487
#define TRAINER_YOUNGSTER_CHAD_3                1488
#define TRAINER_LASS_JANICE_2                   1489
#define TRAINER_LASS_JANICE_3                   1490
#define TRAINER_YOUNGSTER_CHAD_4                1491
#define TRAINER_HIKER_FRANKLIN_2                1492
#define TRAINER_PKMN_PROF_PROF_OAK              1493
#define TRAINER_TEAM_ROCKET_GRUNT_42            1494
#define TRAINER_PSYCHIC_JACLYN                  1495
#define TRAINER_CRUSH_GIRL_SHARON               1496
#define TRAINER_TUBER_AMIRA                     1497
#define TRAINER_PKMN_BREEDER_ALIZE              1498
#define TRAINER_PKMN_RANGER_NICOLAS             1499
#define TRAINER_PKMN_RANGER_MADELINE            1500
#define TRAINER_AROMA_LADY_NIKKI                1501
#define TRAINER_RUIN_MANIAC_STANLY              1502
#define TRAINER_LADY_JACKI                      1503
#define TRAINER_PAINTER_DAISY                   1504
#define TRAINER_BIKER_GOON                      1505
#define TRAINER_BIKER_GOON_2                    1506
#define TRAINER_BIKER_GOON_3                    1507
#define TRAINER_BUG_CATCHER_ANTHONY             1508
#define TRAINER_BUG_CATCHER_CHARLIE             1509
#define TRAINER_TWINS_ELI_ANNE_2                1510
#define TRAINER_YOUNGSTER_JOHNSON               1511
#define TRAINER_BIKER_RICARDO                   1512
#define TRAINER_BIKER_JAREN                     1513
#define TRAINER_TEAM_ROCKET_GRUNT_43            1514
#define TRAINER_TEAM_ROCKET_GRUNT_44            1515
#define TRAINER_TEAM_ROCKET_GRUNT_45            1516
#define TRAINER_TEAM_ROCKET_GRUNT_46            1517
#define TRAINER_TEAM_ROCKET_GRUNT_47            1518
#define TRAINER_TEAM_ROCKET_GRUNT_48            1519
#define TRAINER_TEAM_ROCKET_ADMIN               1520
#define TRAINER_TEAM_ROCKET_ADMIN_2             1521
#define TRAINER_SCIENTIST_GIDEON                1522
#define TRAINER_SWIMMER_FEMALE_AMARA            1523
#define TRAINER_SWIMMER_FEMALE_MARIA            1524
#define TRAINER_SWIMMER_FEMALE_ABIGAIL          1525
#define TRAINER_SWIMMER_MALE_FINN               1526
#define TRAINER_SWIMMER_MALE_GARRETT            1527
#define TRAINER_FISHERMAN_TOMMY                 1528
#define TRAINER_CRUSH_GIRL_TANYA                1529
#define TRAINER_BLACK_BELT_SHEA                 1530
#define TRAINER_BLACK_BELT_HUGH                 1531
#define TRAINER_CAMPER_BRYCE                    1532
#define TRAINER_PICNICKER_CLAIRE                1533
#define TRAINER_CRUSH_KIN_MIK_KIA               1534
#define TRAINER_AROMA_LADY_VIOLET               1535
#define TRAINER_TUBER_ALEXIS                    1536
#define TRAINER_TWINS_JOY_MEG                   1537
#define TRAINER_SWIMMER_FEMALE_TISHA            1538
#define TRAINER_PAINTER_CELINA                  1539
#define TRAINER_PAINTER_RAYNA                   1540
#define TRAINER_LADY_GILLIAN                    1541
#define TRAINER_YOUNGSTER_DESTIN                1542
#define TRAINER_SWIMMER_MALE_TOBY               1543
#define TRAINER_TEAM_ROCKET_GRUNT_49            1544
#define TRAINER_TEAM_ROCKET_GRUNT_50            1545
#define TRAINER_TEAM_ROCKET_GRUNT_51            1546
#define TRAINER_BIRD_KEEPER_MILO                1547
#define TRAINER_BIRD_KEEPER_CHAZ                1548
#define TRAINER_BIRD_KEEPER_HAROLD              1549
#define TRAINER_FISHERMAN_TYLOR                 1550
#define TRAINER_SWIMMER_MALE_MYMO               1551
#define TRAINER_SWIMMER_FEMALE_NICOLE           1552
#define TRAINER_SIS_AND_BRO_AVA_GEB             1553
#define TRAINER_AROMA_LADY_ROSE                 1554
#define TRAINER_SWIMMER_MALE_SAMIR              1555
#define TRAINER_SWIMMER_FEMALE_DENISE           1556
#define TRAINER_TWINS_MIU_MIA                   1557
#define TRAINER_HIKER_EARL                      1558
#define TRAINER_RUIN_MANIAC_FOSTER              1559
#define TRAINER_RUIN_MANIAC_LARRY               1560
#define TRAINER_HIKER_DARYL                     1561
#define TRAINER_POKEMANIAC_HECTOR               1562
#define TRAINER_PSYCHIC_DARIO                   1563
#define TRAINER_PSYCHIC_RODETTE                 1564
#define TRAINER_AROMA_LADY_MIAH                 1565
#define TRAINER_YOUNG_COUPLE_EVE_JON            1566
#define TRAINER_JUGGLER_MASON                   1567
#define TRAINER_CRUSH_GIRL_CYNDY                1568
#define TRAINER_CRUSH_GIRL_JOCELYN              1569
#define TRAINER_TAMER_EVAN                      1570
#define TRAINER_POKEMANIAC_MARK_2               1571
#define TRAINER_PKMN_RANGER_LOGAN               1572
#define TRAINER_PKMN_RANGER_JACKSON             1573
#define TRAINER_PKMN_RANGER_BETH                1574
#define TRAINER_PKMN_RANGER_KATELYN             1575
#define TRAINER_COOLTRAINER_LEROY               1576
#define TRAINER_COOLTRAINER_MICHELLE            1577
#define TRAINER_COOL_COUPLE_LEX_NYA             1578
#define TRAINER_RUIN_MANIAC_BRANDON             1579
#define TRAINER_RUIN_MANIAC_BENJAMIN            1580
#define TRAINER_PAINTER_EDNA                    1581
#define TRAINER_GENTLEMAN_CLIFFORD              1582
#define TRAINER_LADY_SELPHY                     1583
#define TRAINER_RUIN_MANIAC_LAWSON              1584
#define TRAINER_PSYCHIC_LAURA                   1585
#define TRAINER_PKMN_BREEDER_BETHANY            1586
#define TRAINER_PKMN_BREEDER_ALLISON            1587
#define TRAINER_BUG_CATCHER_GARRET              1588
#define TRAINER_BUG_CATCHER_JONAH               1589
#define TRAINER_BUG_CATCHER_VANCE               1590
#define TRAINER_YOUNGSTER_NASH                  1591
#define TRAINER_YOUNGSTER_CORDELL               1592
#define TRAINER_LASS_DALIA                      1593
#define TRAINER_LASS_JOANA                      1594
#define TRAINER_CAMPER_RILEY                    1595
#define TRAINER_PICNICKER_MARCY                 1596
#define TRAINER_RUIN_MANIAC_LAYTON              1597
#define TRAINER_PICNICKER_KELSEY_2              1598
#define TRAINER_PICNICKER_KELSEY_3              1599
#define TRAINER_PICNICKER_KELSEY_4              1600
#define TRAINER_CAMPER_RICKY_2                  1601
#define TRAINER_CAMPER_RICKY_3                  1602
#define TRAINER_CAMPER_RICKY_4                  1603
#define TRAINER_CAMPER_JEFF_2                   1604
#define TRAINER_CAMPER_JEFF_3                   1605
#define TRAINER_CAMPER_JEFF_4                   1606
#define TRAINER_PICNICKER_ISABELLE_2            1607
#define TRAINER_PICNICKER_ISABELLE_3            1608
#define TRAINER_PICNICKER_ISABELLE_4            1609
#define TRAINER_YOUNGSTER_YASU_2                1610
#define TRAINER_YOUNGSTER_YASU_3                1611
#define TRAINER_ENGINEER_BERNIE_2               1612
#define TRAINER_GAMER_DARIAN_2                  1613
#define TRAINER_CAMPER_CHRIS_2                  1614
#define TRAINER_CAMPER_CHRIS_3                  1615
#define TRAINER_CAMPER_CHRIS_4                  1616
#define TRAINER_PICNICKER_ALICIA_2              1617
#define TRAINER_PICNICKER_ALICIA_3              1618
#define TRAINER_PICNICKER_ALICIA_4              1619
#define TRAINER_HIKER_JEREMY_2                  1620
#define TRAINER_POKEMANIAC_MARK_3               1621
#define TRAINER_POKEMANIAC_HERMAN_2             1622
#define TRAINER_POKEMANIAC_HERMAN_3             1623
#define TRAINER_HIKER_TRENT_2                   1624
#define TRAINER_LASS_MEGAN_2                    1625
#define TRAINER_LASS_MEGAN_3                    1626
#define TRAINER_SUPER_NERD_GLENN_2              1627
#define TRAINER_GAMER_RICH_2                    1628
#define TRAINER_BIKER_JAREN_2                   1629
#define TRAINER_FISHERMAN_ELLIOT_2              1630
#define TRAINER_ROCKER_LUCA_2                   1631
#define TRAINER_BEAUTY_SHEILA_2                 1632
#define TRAINER_BIRD_KEEPER_ROBERT_2            1633
#define TRAINER_BIRD_KEEPER_ROBERT_3            1634
#define TRAINER_PICNICKER_SUSIE_2               1635
#define TRAINER_PICNICKER_SUSIE_3               1636
#define TRAINER_PICNICKER_SUSIE_4               1637
#define TRAINER_BIKER_LUKAS_2                   1638
#define TRAINER_BIRD_KEEPER_BENNY_2             1639
#define TRAINER_BIRD_KEEPER_BENNY_3             1640
#define TRAINER_BIRD_KEEPER_MARLON_2            1641
#define TRAINER_BIRD_KEEPER_MARLON_3            1642
#define TRAINER_BEAUTY_GRACE_2                  1643
#define TRAINER_BIRD_KEEPER_CHESTER_2           1644
#define TRAINER_BIRD_KEEPER_CHESTER_3           1645
#define TRAINER_PICNICKER_BECKY_2               1646
#define TRAINER_PICNICKER_BECKY_3               1647
#define TRAINER_PICNICKER_BECKY_4               1648
#define TRAINER_CRUSH_KIN_RON_MYA_2             1649
#define TRAINER_CRUSH_KIN_RON_MYA_3             1650
#define TRAINER_CRUSH_KIN_RON_MYA_4             1651
#define TRAINER_BIKER_RUBEN_2                   1652
#define TRAINER_CUE_BALL_CAMRON_2               1653
#define TRAINER_BIKER_JAXON_2                   1654
#define TRAINER_CUE_BALL_ISAIAH_2               1655
#define TRAINER_CUE_BALL_COREY_2                1656
#define TRAINER_BIRD_KEEPER_JACOB_2             1657
#define TRAINER_BIRD_KEEPER_JACOB_3             1658
#define TRAINER_SWIMMER_FEMALE_ALICE_2          1659
#define TRAINER_SWIMMER_MALE_DARRIN_2           1660
#define TRAINER_PICNICKER_MISSY_2               1661
#define TRAINER_PICNICKER_MISSY_3               1662
#define TRAINER_FISHERMAN_WADE_2                1663
#define TRAINER_SWIMMER_MALE_JACK_2             1664
#define TRAINER_SIS_AND_BRO_LIL_IAN_2           1665
#define TRAINER_SIS_AND_BRO_LIL_IAN_3           1666
#define TRAINER_SWIMMER_MALE_FINN_2             1667
#define TRAINER_CRUSH_GIRL_SHARON_2             1668
#define TRAINER_CRUSH_GIRL_SHARON_3             1669
#define TRAINER_CRUSH_GIRL_TANYA_2              1670
#define TRAINER_CRUSH_GIRL_TANYA_3              1671
#define TRAINER_BLACK_BELT_SHEA_2               1672
#define TRAINER_BLACK_BELT_SHEA_3               1673
#define TRAINER_BLACK_BELT_HUGH_2               1674
#define TRAINER_BLACK_BELT_HUGH_3               1675
#define TRAINER_CRUSH_KIN_MIK_KIA_2             1676
#define TRAINER_CRUSH_KIN_MIK_KIA_3             1677
#define TRAINER_TUBER_AMIRA_2                   1678
#define TRAINER_TWINS_JOY_MEG_2                 1679
#define TRAINER_PAINTER_RAYNA_2                 1680
#define TRAINER_YOUNGSTER_DESTIN_2              1681
#define TRAINER_PKMN_BREEDER_ALIZE_2            1682
#define TRAINER_YOUNG_COUPLE_GIA_JES_2          1683
#define TRAINER_YOUNG_COUPLE_GIA_JES_3          1684
#define TRAINER_BIRD_KEEPER_MILO_2              1685
#define TRAINER_BIRD_KEEPER_CHAZ_2              1686
#define TRAINER_BIRD_KEEPER_HAROLD_2            1687
#define TRAINER_SWIMMER_FEMALE_NICOLE_2         1688
#define TRAINER_PSYCHIC_JACLYN_2                1689
#define TRAINER_SWIMMER_MALE_SAMIR_2            1690
#define TRAINER_HIKER_EARL_2                    1691
#define TRAINER_RUIN_MANIAC_LARRY_2             1692
#define TRAINER_POKEMANIAC_HECTOR_2             1693
#define TRAINER_PSYCHIC_DARIO_2                 1694
#define TRAINER_PSYCHIC_RODETTE_2               1695
#define TRAINER_JUGGLER_MASON_2                 1696
#define TRAINER_PKMN_RANGER_NICOLAS_2           1697
#define TRAINER_PKMN_RANGER_MADELINE_2          1698
#define TRAINER_CRUSH_GIRL_CYNDY_2              1699
#define TRAINER_TAMER_EVAN_2                    1700
#define TRAINER_PKMN_RANGER_JACKSON_2           1701
#define TRAINER_PKMN_RANGER_KATELYN_2           1702
#define TRAINER_COOLTRAINER_LEROY_2             1703
#define TRAINER_COOLTRAINER_MICHELLE_2          1704
#define TRAINER_COOL_COUPLE_LEX_NYA_2           1705
#define TRAINER_BUG_CATCHER_COLTON_2            1706
#define TRAINER_BUG_CATCHER_COLTON_3            1707
#define TRAINER_BUG_CATCHER_COLTON_4            1708
#define TRAINER_SWIMMER_MALE_MATTHEW_2          1709
#define TRAINER_SWIMMER_MALE_TONY_2             1710
#define TRAINER_SWIMMER_FEMALE_MELISSA_2        1711
#define TRAINER_ELITE_FOUR_LORELEI_2            1712
#define TRAINER_ELITE_FOUR_BRUNO_2              1713
#define TRAINER_ELITE_FOUR_AGATHA_2             1714
#define TRAINER_ELITE_FOUR_LANCE_2              1715
#define TRAINER_CHAMPION_REMATCH_SQUIRTLE       1716
#define TRAINER_CHAMPION_REMATCH_BULBASAUR      1717
#define TRAINER_CHAMPION_REMATCH_CHARMANDER     1718
#define TRAINER_CUE_BALL_PAXTON                 1719
// Johto Silver league daily-rematch parties (real HnS _7 teams). New trainers
// live in the Kanto bank's spare defeat-flag ids (SaveBlock3), never in the
// frozen Hoenn+Johto window (see opponents.h).
#define TRAINER_RIVAL_INDIGO_CHIKORITA          1720
#define TRAINER_RIVAL_INDIGO_CYNDAQUIL          1721
#define TRAINER_RIVAL_INDIGO_TOTODILE           1722
#define TRAINER_ROCKET_JESSIE                   1723
#define TRAINER_ROCKET_JAMES                    1724
#define TRAINER_ROCKET_JESSIE_2                 1725
#define TRAINER_ROCKET_JAMES_2                  1726
#else
#define TRAINER_YOUNGSTER_BEN                   1
#define TRAINER_YOUNGSTER_CALVIN                2
#define TRAINER_YOUNGSTER_JOSH                  3
#define TRAINER_YOUNGSTER_TIMMY                 4
#define TRAINER_YOUNGSTER_JOEY                  5
#define TRAINER_YOUNGSTER_DAN                   6
#define TRAINER_YOUNGSTER_CHAD                  7
#define TRAINER_YOUNGSTER_TYLER                 8
#define TRAINER_YOUNGSTER_EDDIE                 9
#define TRAINER_YOUNGSTER_DILLON                10
#define TRAINER_YOUNGSTER_YASU                  11
#define TRAINER_YOUNGSTER_DAVE                  12
#define TRAINER_YOUNGSTER_BEN_2                 13
#define TRAINER_BUG_CATCHER_RICK                14
#define TRAINER_BUG_CATCHER_DOUG                15
#define TRAINER_BUG_CATCHER_SAMMY               16
#define TRAINER_BUG_CATCHER_COLTON              17
#define TRAINER_BUG_CATCHER_GREG                18
#define TRAINER_BUG_CATCHER_JAMES               19
#define TRAINER_BUG_CATCHER_KENT                20
#define TRAINER_BUG_CATCHER_ROBBY               21
#define TRAINER_BUG_CATCHER_CALE                22
#define TRAINER_BUG_CATCHER_KEIGO               23
#define TRAINER_BUG_CATCHER_ELIJAH              24
#define TRAINER_BUG_CATCHER_BRENT               25
#define TRAINER_BUG_CATCHER_CONNER              26
#define TRAINER_LASS_JANICE                     27
#define TRAINER_LASS_SALLY                      28
#define TRAINER_LASS_ROBIN                      29
#define TRAINER_LASS_CRISSY                     30
#define TRAINER_LASS_MIRIAM                     31
#define TRAINER_LASS_IRIS                       32
#define TRAINER_LASS_RELI                       33
#define TRAINER_LASS_ALI                        34
#define TRAINER_LASS_HALEY                      35
#define TRAINER_LASS_ANN                        36
#define TRAINER_LASS_DAWN                       37
#define TRAINER_LASS_PAIGE                      38
#define TRAINER_LASS_ANDREA                     39
#define TRAINER_LASS_MEGAN                      40
#define TRAINER_LASS_JULIA                      41
#define TRAINER_LASS_KAY                        42
#define TRAINER_LASS_LISA                       43
#define TRAINER_SAILOR_EDMOND                   44
#define TRAINER_SAILOR_TREVOR                   45
#define TRAINER_SAILOR_LEONARD                  46
#define TRAINER_SAILOR_DUNCAN                   47
#define TRAINER_SAILOR_HUEY                     48
#define TRAINER_SAILOR_DYLAN                    49
#define TRAINER_SAILOR_PHILLIP                  50
#define TRAINER_SAILOR_DWAYNE                   51
#define TRAINER_CAMPER_LIAM                     52
#define TRAINER_CAMPER_SHANE                    53
#define TRAINER_CAMPER_ETHAN                    54
#define TRAINER_CAMPER_RICKY                    55
#define TRAINER_CAMPER_JEFF                     56
#define TRAINER_CAMPER_CHRIS                    57
#define TRAINER_CAMPER_DREW                     58
#define TRAINER_PICNICKER_DIANA                 59
#define TRAINER_PICNICKER_NANCY                 60
#define TRAINER_PICNICKER_ISABELLE              61
#define TRAINER_PICNICKER_KELSEY                62
#define TRAINER_PICNICKER_ALICIA                63
#define TRAINER_PICNICKER_CAITLIN               64
#define TRAINER_PICNICKER_HEIDI                 65
#define TRAINER_PICNICKER_CAROL                 66
#define TRAINER_PICNICKER_SOFIA                 67
#define TRAINER_PICNICKER_MARTHA                68
#define TRAINER_PICNICKER_TINA                  69
#define TRAINER_PICNICKER_HANNAH                70
#define TRAINER_POKEMANIAC_MARK                 71
#define TRAINER_POKEMANIAC_HERMAN               72
#define TRAINER_POKEMANIAC_COOPER               73
#define TRAINER_POKEMANIAC_STEVE                74
#define TRAINER_POKEMANIAC_WINSTON              75
#define TRAINER_POKEMANIAC_DAWSON               76
#define TRAINER_POKEMANIAC_ASHTON               77
#define TRAINER_SUPER_NERD_JOVAN                78
#define TRAINER_SUPER_NERD_MIGUEL               79
#define TRAINER_SUPER_NERD_AIDAN                80
#define TRAINER_SUPER_NERD_GLENN                81
#define TRAINER_SUPER_NERD_LESLIE               82
#define TRAINER_SUPER_NERD_ERIK                 83
#define TRAINER_SUPER_NERD_AVERY                84
#define TRAINER_SUPER_NERD_DEREK                85
#define TRAINER_SUPER_NERD_ZAC                  86
#define TRAINER_HIKER_MARCOS                    87
#define TRAINER_HIKER_FRANKLIN                  88
#define TRAINER_HIKER_NOB                       89
#define TRAINER_HIKER_WAYNE                     90
#define TRAINER_HIKER_ALAN                      91
#define TRAINER_HIKER_BRICE                     92
#define TRAINER_HIKER_CLARK                     93
#define TRAINER_HIKER_TRENT                     94
#define TRAINER_HIKER_DUDLEY                    95
#define TRAINER_HIKER_ALLEN                     96
#define TRAINER_HIKER_ERIC                      97
#define TRAINER_HIKER_LENNY                     98
#define TRAINER_HIKER_OLIVER                    99
#define TRAINER_HIKER_LUCAS                     100
#define TRAINER_BIKER_JARED                     101
#define TRAINER_BIKER_MALIK                     102
#define TRAINER_BIKER_ERNEST                    103
#define TRAINER_BIKER_ALEX                      104
#define TRAINER_BIKER_LAO                       105
#define TRAINER_BIKER_HIDEO                     106
#define TRAINER_BIKER_RUBEN                     107
#define TRAINER_BIKER_BILLY                     108
#define TRAINER_BIKER_NIKOLAS                   109
#define TRAINER_BIKER_JAXON                     110
#define TRAINER_BIKER_WILLIAM                   111
#define TRAINER_BIKER_LUKAS                     112
#define TRAINER_BIKER_ISAAC                     113
#define TRAINER_BIKER_GERALD                    114
#define TRAINER_BURGLAR_QUINN                   115
#define TRAINER_BURGLAR_RAMON                   116
#define TRAINER_BURGLAR_DUSTY                   117
#define TRAINER_BURGLAR_ARNIE                   118
#define TRAINER_BURGLAR_SIMON                   119
#define TRAINER_BURGLAR_LEWIS                   120
#define TRAINER_ENGINEER_BAILY                  121
#define TRAINER_ENGINEER_BRAXTON                122
#define TRAINER_ENGINEER_BERNIE                 123
#define TRAINER_FISHERMAN_DALE                  124
#define TRAINER_FISHERMAN_BARNY                 125
#define TRAINER_FISHERMAN_NED                   126
#define TRAINER_FISHERMAN_CHIP                  127
#define TRAINER_FISHERMAN_HANK                  128
#define TRAINER_FISHERMAN_ELLIOT                129
#define TRAINER_FISHERMAN_RONALD                130
#define TRAINER_FISHERMAN_CLAUDE                131
#define TRAINER_FISHERMAN_WADE                  132
#define TRAINER_FISHERMAN_NOLAN                 133
#define TRAINER_FISHERMAN_ANDREW                134
#define TRAINER_SWIMMER_MALE_LUIS               135
#define TRAINER_SWIMMER_MALE_RICHARD            136
#define TRAINER_SWIMMER_MALE_REECE              137
#define TRAINER_SWIMMER_MALE_MATTHEW            138
#define TRAINER_SWIMMER_MALE_DOUGLAS            139
#define TRAINER_SWIMMER_MALE_DAVID              140
#define TRAINER_SWIMMER_MALE_TONY               141
#define TRAINER_SWIMMER_MALE_AXLE               142
#define TRAINER_SWIMMER_MALE_BARRY              143
#define TRAINER_SWIMMER_MALE_DEAN               144
#define TRAINER_SWIMMER_MALE_DARRIN             145
#define TRAINER_SWIMMER_MALE_SPENCER            146
#define TRAINER_SWIMMER_MALE_JACK               147
#define TRAINER_SWIMMER_MALE_JEROME             148
#define TRAINER_SWIMMER_MALE_ROLAND             149
#define TRAINER_CUE_BALL_KOJI                   150
#define TRAINER_CUE_BALL_LUKE                   151
#define TRAINER_CUE_BALL_CAMRON                 152
#define TRAINER_CUE_BALL_RAUL                   153
#define TRAINER_CUE_BALL_ISAIAH                 154
#define TRAINER_CUE_BALL_ZEEK                   155
#define TRAINER_CUE_BALL_JAMAL                  156
#define TRAINER_CUE_BALL_COREY                  157
#define TRAINER_CUE_BALL_CHASE                  158
#define TRAINER_GAMER_HUGO                      159
#define TRAINER_GAMER_JASPER                    160
#define TRAINER_GAMER_DIRK                      161
#define TRAINER_GAMER_DARIAN                    162
#define TRAINER_GAMER_STAN                      163
#define TRAINER_GAMER_RICH                      164
#define TRAINER_BEAUTY_BRIDGET                  165
#define TRAINER_BEAUTY_TAMIA                    166
#define TRAINER_BEAUTY_LORI                     167
#define TRAINER_BEAUTY_LOLA                     168
#define TRAINER_BEAUTY_SHEILA                   169
#define TRAINER_SWIMMER_FEMALE_TIFFANY          170
#define TRAINER_SWIMMER_FEMALE_NORA             171
#define TRAINER_SWIMMER_FEMALE_MELISSA          172
#define TRAINER_BEAUTY_GRACE                    173
#define TRAINER_BEAUTY_OLIVIA                   174
#define TRAINER_BEAUTY_LAUREN                   175
#define TRAINER_SWIMMER_FEMALE_ANYA             176
#define TRAINER_SWIMMER_FEMALE_ALICE            177
#define TRAINER_SWIMMER_FEMALE_CONNIE           178
#define TRAINER_SWIMMER_FEMALE_SHIRLEY          179
#define TRAINER_PSYCHIC_JOHAN                   180
#define TRAINER_PSYCHIC_TYRON                   181
#define TRAINER_PSYCHIC_CAMERON                 182
#define TRAINER_PSYCHIC_PRESTON                 183
#define TRAINER_ROCKER_RANDALL                  184
#define TRAINER_ROCKER_LUCA                     185
#define TRAINER_JUGGLER_DALTON                  186
#define TRAINER_JUGGLER_NELSON                  187
#define TRAINER_JUGGLER_KIRK                    188
#define TRAINER_JUGGLER_SHAWN                   189
#define TRAINER_JUGGLER_GREGORY                 190
#define TRAINER_JUGGLER_EDWARD                  191
#define TRAINER_JUGGLER_KAYDEN                  192
#define TRAINER_JUGGLER_NATE                    193
#define TRAINER_TAMER_PHIL                      194
#define TRAINER_TAMER_EDGAR                     195
#define TRAINER_TAMER_JASON                     196
#define TRAINER_TAMER_COLE                      197
#define TRAINER_TAMER_VINCENT                   198
#define TRAINER_TAMER_JOHN                      199
#define TRAINER_BIRD_KEEPER_SEBASTIAN           200
#define TRAINER_BIRD_KEEPER_PERRY               201
#define TRAINER_BIRD_KEEPER_ROBERT              202
#define TRAINER_BIRD_KEEPER_DONALD              203
#define TRAINER_BIRD_KEEPER_BENNY               204
#define TRAINER_BIRD_KEEPER_EDWIN               205
#define TRAINER_BIRD_KEEPER_CHESTER             206
#define TRAINER_BIRD_KEEPER_WILTON              207
#define TRAINER_BIRD_KEEPER_RAMIRO              208
#define TRAINER_BIRD_KEEPER_JACOB               209
#define TRAINER_BIRD_KEEPER_ROGER               210
#define TRAINER_BIRD_KEEPER_REED                211
#define TRAINER_BIRD_KEEPER_KEITH               212
#define TRAINER_BIRD_KEEPER_CARTER              213
#define TRAINER_BIRD_KEEPER_MITCH               214
#define TRAINER_BIRD_KEEPER_BECK                215
#define TRAINER_BIRD_KEEPER_MARLON              216
#define TRAINER_BLACK_BELT_KOICHI               217
#define TRAINER_BLACK_BELT_MIKE                 218
#define TRAINER_BLACK_BELT_HIDEKI               219
#define TRAINER_BLACK_BELT_AARON                220
#define TRAINER_BLACK_BELT_HITOSHI              221
#define TRAINER_BLACK_BELT_ATSUSHI              222
#define TRAINER_BLACK_BELT_KIYO                 223
#define TRAINER_BLACK_BELT_TAKASHI              224
#define TRAINER_BLACK_BELT_DAISUKE              225
#define TRAINER_RIVAL_OAKS_LAB_SQUIRTLE         226
#define TRAINER_RIVAL_OAKS_LAB_BULBASAUR        227
#define TRAINER_RIVAL_OAKS_LAB_CHARMANDER       228
#define TRAINER_RIVAL_ROUTE22_EARLY_SQUIRTLE    229
#define TRAINER_RIVAL_ROUTE22_EARLY_BULBASAUR   230
#define TRAINER_RIVAL_ROUTE22_EARLY_CHARMANDER  231
#define TRAINER_RIVAL_CERULEAN_SQUIRTLE         232
#define TRAINER_RIVAL_CERULEAN_BULBASAUR        233
#define TRAINER_RIVAL_CERULEAN_CHARMANDER       234
#define TRAINER_SCIENTIST_TED                   235
#define TRAINER_SCIENTIST_CONNOR                236
#define TRAINER_SCIENTIST_JERRY                 237
#define TRAINER_SCIENTIST_JOSE                  238
#define TRAINER_SCIENTIST_RODNEY                239
#define TRAINER_SCIENTIST_BEAU                  240
#define TRAINER_SCIENTIST_TAYLOR                241
#define TRAINER_SCIENTIST_JOSHUA                242
#define TRAINER_SCIENTIST_PARKER                243
#define TRAINER_SCIENTIST_ED                    244
#define TRAINER_SCIENTIST_TRAVIS                245
#define TRAINER_SCIENTIST_BRAYDON               246
#define TRAINER_SCIENTIST_IVAN                  247
#define TRAINER_BOSS_GIOVANNI                   248
#define TRAINER_BOSS_GIOVANNI_2                 249
#define TRAINER_LEADER_GIOVANNI                 250
#define TRAINER_TEAM_ROCKET_GRUNT               251
#define TRAINER_TEAM_ROCKET_GRUNT_2             252
#define TRAINER_TEAM_ROCKET_GRUNT_3             253
#define TRAINER_TEAM_ROCKET_GRUNT_4             254
#define TRAINER_TEAM_ROCKET_GRUNT_5             255
#define TRAINER_TEAM_ROCKET_GRUNT_6             256
#define TRAINER_TEAM_ROCKET_GRUNT_7             257
#define TRAINER_TEAM_ROCKET_GRUNT_8             258
#define TRAINER_TEAM_ROCKET_GRUNT_9             259
#define TRAINER_TEAM_ROCKET_GRUNT_10            260
#define TRAINER_TEAM_ROCKET_GRUNT_11            261
#define TRAINER_TEAM_ROCKET_GRUNT_12            262
#define TRAINER_TEAM_ROCKET_GRUNT_13            263
#define TRAINER_TEAM_ROCKET_GRUNT_14            264
#define TRAINER_TEAM_ROCKET_GRUNT_15            265
#define TRAINER_TEAM_ROCKET_GRUNT_16            266
#define TRAINER_TEAM_ROCKET_GRUNT_17            267
#define TRAINER_TEAM_ROCKET_GRUNT_18            268
#define TRAINER_TEAM_ROCKET_GRUNT_19            269
#define TRAINER_TEAM_ROCKET_GRUNT_20            270
#define TRAINER_TEAM_ROCKET_GRUNT_21            271
#define TRAINER_TEAM_ROCKET_GRUNT_22            272
#define TRAINER_TEAM_ROCKET_GRUNT_23            273
#define TRAINER_TEAM_ROCKET_GRUNT_24            274
#define TRAINER_TEAM_ROCKET_GRUNT_25            275
#define TRAINER_TEAM_ROCKET_GRUNT_26            276
#define TRAINER_TEAM_ROCKET_GRUNT_27            277
#define TRAINER_TEAM_ROCKET_GRUNT_28            278
#define TRAINER_TEAM_ROCKET_GRUNT_29            279
#define TRAINER_TEAM_ROCKET_GRUNT_30            280
#define TRAINER_TEAM_ROCKET_GRUNT_31            281
#define TRAINER_TEAM_ROCKET_GRUNT_32            282
#define TRAINER_TEAM_ROCKET_GRUNT_33            283
#define TRAINER_TEAM_ROCKET_GRUNT_34            284
#define TRAINER_TEAM_ROCKET_GRUNT_35            285
#define TRAINER_TEAM_ROCKET_GRUNT_36            286
#define TRAINER_TEAM_ROCKET_GRUNT_37            287
#define TRAINER_TEAM_ROCKET_GRUNT_38            288
#define TRAINER_TEAM_ROCKET_GRUNT_39            289
#define TRAINER_TEAM_ROCKET_GRUNT_40            290
#define TRAINER_TEAM_ROCKET_GRUNT_41            291
#define TRAINER_COOLTRAINER_SAMUEL              292
#define TRAINER_COOLTRAINER_GEORGE              293
#define TRAINER_COOLTRAINER_COLBY               294
#define TRAINER_COOLTRAINER_PAUL                295
#define TRAINER_COOLTRAINER_ROLANDO             296
#define TRAINER_COOLTRAINER_GILBERT             297
#define TRAINER_COOLTRAINER_OWEN                298
#define TRAINER_COOLTRAINER_BERKE               299
#define TRAINER_COOLTRAINER_YUJI                300
#define TRAINER_COOLTRAINER_WARREN              301
#define TRAINER_COOLTRAINER_MARY                302
#define TRAINER_COOLTRAINER_CAROLINE            303
#define TRAINER_COOLTRAINER_ALEXA               304
#define TRAINER_COOLTRAINER_SHANNON             305
#define TRAINER_COOLTRAINER_NAOMI               306
#define TRAINER_COOLTRAINER_BROOKE              307
#define TRAINER_COOLTRAINER_AUSTINA             308
#define TRAINER_COOLTRAINER_JULIE               309
#define TRAINER_ELITE_FOUR_LORELEI              310
#define TRAINER_ELITE_FOUR_BRUNO                311
#define TRAINER_ELITE_FOUR_AGATHA               312
#define TRAINER_ELITE_FOUR_LANCE                313
#define TRAINER_LEADER_BROCK                    314
#define TRAINER_LEADER_MISTY                    315
#define TRAINER_LEADER_LT_SURGE                 316
#define TRAINER_LEADER_ERIKA                    317
#define TRAINER_LEADER_KOGA                     318
#define TRAINER_LEADER_BLAINE                   319
#define TRAINER_LEADER_SABRINA                  320
#define TRAINER_GENTLEMAN_THOMAS                321
#define TRAINER_GENTLEMAN_ARTHUR                322
#define TRAINER_GENTLEMAN_TUCKER                323
#define TRAINER_GENTLEMAN_NORTON                324
#define TRAINER_GENTLEMAN_WALTER                325
#define TRAINER_RIVAL_SS_ANNE_SQUIRTLE          326
#define TRAINER_RIVAL_SS_ANNE_BULBASAUR         327
#define TRAINER_RIVAL_SS_ANNE_CHARMANDER        328
#define TRAINER_RIVAL_POKEMON_TOWER_SQUIRTLE    329
#define TRAINER_RIVAL_POKEMON_TOWER_BULBASAUR   330
#define TRAINER_RIVAL_POKEMON_TOWER_CHARMANDER  331
#define TRAINER_RIVAL_SILPH_SQUIRTLE            332
#define TRAINER_RIVAL_SILPH_BULBASAUR           333
#define TRAINER_RIVAL_SILPH_CHARMANDER          334
#define TRAINER_RIVAL_ROUTE22_LATE_SQUIRTLE     335
#define TRAINER_RIVAL_ROUTE22_LATE_BULBASAUR    336
#define TRAINER_RIVAL_ROUTE22_LATE_CHARMANDER   337
#define TRAINER_CHAMPION_FIRST_SQUIRTLE         338
#define TRAINER_CHAMPION_FIRST_BULBASAUR        339
#define TRAINER_CHAMPION_FIRST_CHARMANDER       340
#define TRAINER_CHANNELER_PATRICIA              341
#define TRAINER_CHANNELER_CARLY                 342
#define TRAINER_CHANNELER_HOPE                  343
#define TRAINER_CHANNELER_PAULA                 344
#define TRAINER_CHANNELER_LAUREL                345
#define TRAINER_CHANNELER_JODY                  346
#define TRAINER_CHANNELER_TAMMY                 347
#define TRAINER_CHANNELER_RUTH                  348
#define TRAINER_CHANNELER_KARINA                349
#define TRAINER_CHANNELER_JANAE                 350
#define TRAINER_CHANNELER_ANGELICA              351
#define TRAINER_CHANNELER_EMILIA                352
#define TRAINER_CHANNELER_JENNIFER              353
#define TRAINER_CHANNELER_AMANDA                354
#define TRAINER_CHANNELER_STACY                 355
#define TRAINER_CHANNELER_TASHA                 356
#define TRAINER_HIKER_JEREMY                    357
#define TRAINER_PICNICKER_ALMA                  358
#define TRAINER_PICNICKER_SUSIE                 359
#define TRAINER_PICNICKER_VALERIE               360
#define TRAINER_PICNICKER_GWEN                  361
#define TRAINER_BIKER_VIRGIL                    362
#define TRAINER_CAMPER_FLINT                    363
#define TRAINER_PICNICKER_MISSY                 364
#define TRAINER_PICNICKER_IRENE                 365
#define TRAINER_PICNICKER_DANA                  366
#define TRAINER_PICNICKER_ARIANA                367
#define TRAINER_PICNICKER_LEAH                  368
#define TRAINER_CAMPER_JUSTIN                   369
#define TRAINER_PICNICKER_YAZMIN                370
#define TRAINER_PICNICKER_KINDRA                371
#define TRAINER_PICNICKER_BECKY                 372
#define TRAINER_PICNICKER_CELIA                 373
#define TRAINER_GENTLEMAN_BROOKS                374
#define TRAINER_GENTLEMAN_LAMAR                 375
#define TRAINER_TWINS_ELI_ANNE                  376
#define TRAINER_COOL_COUPLE_RAY_TYRA            377
#define TRAINER_YOUNG_COUPLE_GIA_JES            378
#define TRAINER_TWINS_KIRI_JAN                  379
#define TRAINER_CRUSH_KIN_RON_MYA               380
#define TRAINER_YOUNG_COUPLE_LEA_JED            381
#define TRAINER_SIS_AND_BRO_LIA_LUC             382
#define TRAINER_SIS_AND_BRO_LIL_IAN             383
#define TRAINER_YOUNGSTER_BEN_3                 384
#define TRAINER_YOUNGSTER_BEN_4                 385
#define TRAINER_YOUNGSTER_CHAD_2                386
#define TRAINER_LASS_RELI_2                     387
#define TRAINER_LASS_RELI_3                     388
#define TRAINER_YOUNGSTER_TIMMY_2               389
#define TRAINER_YOUNGSTER_TIMMY_3               390
#define TRAINER_YOUNGSTER_TIMMY_4               391
#define TRAINER_YOUNGSTER_CHAD_3                392
#define TRAINER_LASS_JANICE_2                   393
#define TRAINER_LASS_JANICE_3                   394
#define TRAINER_YOUNGSTER_CHAD_4                395
#define TRAINER_HIKER_FRANKLIN_2                396
#define TRAINER_PKMN_PROF_PROF_OAK              397
#define TRAINER_TEAM_ROCKET_GRUNT_42            398
#define TRAINER_PSYCHIC_JACLYN                  399
#define TRAINER_CRUSH_GIRL_SHARON               400
#define TRAINER_TUBER_AMIRA                     401
#define TRAINER_PKMN_BREEDER_ALIZE              402
#define TRAINER_PKMN_RANGER_NICOLAS             403
#define TRAINER_PKMN_RANGER_MADELINE            404
#define TRAINER_AROMA_LADY_NIKKI                405
#define TRAINER_RUIN_MANIAC_STANLY              406
#define TRAINER_LADY_JACKI                      407
#define TRAINER_PAINTER_DAISY                   408
#define TRAINER_BIKER_GOON                      409
#define TRAINER_BIKER_GOON_2                    410
#define TRAINER_BIKER_GOON_3                    411
#define TRAINER_BUG_CATCHER_ANTHONY             412
#define TRAINER_BUG_CATCHER_CHARLIE             413
#define TRAINER_TWINS_ELI_ANNE_2                414
#define TRAINER_YOUNGSTER_JOHNSON               415
#define TRAINER_BIKER_RICARDO                   416
#define TRAINER_BIKER_JAREN                     417
#define TRAINER_TEAM_ROCKET_GRUNT_43            418
#define TRAINER_TEAM_ROCKET_GRUNT_44            419
#define TRAINER_TEAM_ROCKET_GRUNT_45            420
#define TRAINER_TEAM_ROCKET_GRUNT_46            421
#define TRAINER_TEAM_ROCKET_GRUNT_47            422
#define TRAINER_TEAM_ROCKET_GRUNT_48            423
#define TRAINER_TEAM_ROCKET_ADMIN               424
#define TRAINER_TEAM_ROCKET_ADMIN_2             425
#define TRAINER_SCIENTIST_GIDEON                426
#define TRAINER_SWIMMER_FEMALE_AMARA            427
#define TRAINER_SWIMMER_FEMALE_MARIA            428
#define TRAINER_SWIMMER_FEMALE_ABIGAIL          429
#define TRAINER_SWIMMER_MALE_FINN               430
#define TRAINER_SWIMMER_MALE_GARRETT            431
#define TRAINER_FISHERMAN_TOMMY                 432
#define TRAINER_CRUSH_GIRL_TANYA                433
#define TRAINER_BLACK_BELT_SHEA                 434
#define TRAINER_BLACK_BELT_HUGH                 435
#define TRAINER_CAMPER_BRYCE                    436
#define TRAINER_PICNICKER_CLAIRE                437
#define TRAINER_CRUSH_KIN_MIK_KIA               438
#define TRAINER_AROMA_LADY_VIOLET               439
#define TRAINER_TUBER_ALEXIS                    440
#define TRAINER_TWINS_JOY_MEG                   441
#define TRAINER_SWIMMER_FEMALE_TISHA            442
#define TRAINER_PAINTER_CELINA                  443
#define TRAINER_PAINTER_RAYNA                   444
#define TRAINER_LADY_GILLIAN                    445
#define TRAINER_YOUNGSTER_DESTIN                446
#define TRAINER_SWIMMER_MALE_TOBY               447
#define TRAINER_TEAM_ROCKET_GRUNT_49            448
#define TRAINER_TEAM_ROCKET_GRUNT_50            449
#define TRAINER_TEAM_ROCKET_GRUNT_51            450
#define TRAINER_BIRD_KEEPER_MILO                451
#define TRAINER_BIRD_KEEPER_CHAZ                452
#define TRAINER_BIRD_KEEPER_HAROLD              453
#define TRAINER_FISHERMAN_TYLOR                 454
#define TRAINER_SWIMMER_MALE_MYMO               455
#define TRAINER_SWIMMER_FEMALE_NICOLE           456
#define TRAINER_SIS_AND_BRO_AVA_GEB             457
#define TRAINER_AROMA_LADY_ROSE                 458
#define TRAINER_SWIMMER_MALE_SAMIR              459
#define TRAINER_SWIMMER_FEMALE_DENISE           460
#define TRAINER_TWINS_MIU_MIA                   461
#define TRAINER_HIKER_EARL                      462
#define TRAINER_RUIN_MANIAC_FOSTER              463
#define TRAINER_RUIN_MANIAC_LARRY               464
#define TRAINER_HIKER_DARYL                     465
#define TRAINER_POKEMANIAC_HECTOR               466
#define TRAINER_PSYCHIC_DARIO                   467
#define TRAINER_PSYCHIC_RODETTE                 468
#define TRAINER_AROMA_LADY_MIAH                 469
#define TRAINER_YOUNG_COUPLE_EVE_JON            470
#define TRAINER_JUGGLER_MASON                   471
#define TRAINER_CRUSH_GIRL_CYNDY                472
#define TRAINER_CRUSH_GIRL_JOCELYN              473
#define TRAINER_TAMER_EVAN                      474
#define TRAINER_POKEMANIAC_MARK_2               475
#define TRAINER_PKMN_RANGER_LOGAN               476
#define TRAINER_PKMN_RANGER_JACKSON             477
#define TRAINER_PKMN_RANGER_BETH                478
#define TRAINER_PKMN_RANGER_KATELYN             479
#define TRAINER_COOLTRAINER_LEROY               480
#define TRAINER_COOLTRAINER_MICHELLE            481
#define TRAINER_COOL_COUPLE_LEX_NYA             482
#define TRAINER_RUIN_MANIAC_BRANDON             483
#define TRAINER_RUIN_MANIAC_BENJAMIN            484
#define TRAINER_PAINTER_EDNA                    485
#define TRAINER_GENTLEMAN_CLIFFORD              486
#define TRAINER_LADY_SELPHY                     487
#define TRAINER_RUIN_MANIAC_LAWSON              488
#define TRAINER_PSYCHIC_LAURA                   489
#define TRAINER_PKMN_BREEDER_BETHANY            490
#define TRAINER_PKMN_BREEDER_ALLISON            491
#define TRAINER_BUG_CATCHER_GARRET              492
#define TRAINER_BUG_CATCHER_JONAH               493
#define TRAINER_BUG_CATCHER_VANCE               494
#define TRAINER_YOUNGSTER_NASH                  495
#define TRAINER_YOUNGSTER_CORDELL               496
#define TRAINER_LASS_DALIA                      497
#define TRAINER_LASS_JOANA                      498
#define TRAINER_CAMPER_RILEY                    499
#define TRAINER_PICNICKER_MARCY                 500
#define TRAINER_RUIN_MANIAC_LAYTON              501
#define TRAINER_PICNICKER_KELSEY_2              502
#define TRAINER_PICNICKER_KELSEY_3              503
#define TRAINER_PICNICKER_KELSEY_4              504
#define TRAINER_CAMPER_RICKY_2                  505
#define TRAINER_CAMPER_RICKY_3                  506
#define TRAINER_CAMPER_RICKY_4                  507
#define TRAINER_CAMPER_JEFF_2                   508
#define TRAINER_CAMPER_JEFF_3                   509
#define TRAINER_CAMPER_JEFF_4                   510
#define TRAINER_PICNICKER_ISABELLE_2            511
#define TRAINER_PICNICKER_ISABELLE_3            512
#define TRAINER_PICNICKER_ISABELLE_4            513
#define TRAINER_YOUNGSTER_YASU_2                514
#define TRAINER_YOUNGSTER_YASU_3                515
#define TRAINER_ENGINEER_BERNIE_2               516
#define TRAINER_GAMER_DARIAN_2                  517
#define TRAINER_CAMPER_CHRIS_2                  518
#define TRAINER_CAMPER_CHRIS_3                  519
#define TRAINER_CAMPER_CHRIS_4                  520
#define TRAINER_PICNICKER_ALICIA_2              521
#define TRAINER_PICNICKER_ALICIA_3              522
#define TRAINER_PICNICKER_ALICIA_4              523
#define TRAINER_HIKER_JEREMY_2                  524
#define TRAINER_POKEMANIAC_MARK_3               525
#define TRAINER_POKEMANIAC_HERMAN_2             526
#define TRAINER_POKEMANIAC_HERMAN_3             527
#define TRAINER_HIKER_TRENT_2                   528
#define TRAINER_LASS_MEGAN_2                    529
#define TRAINER_LASS_MEGAN_3                    530
#define TRAINER_SUPER_NERD_GLENN_2              531
#define TRAINER_GAMER_RICH_2                    532
#define TRAINER_BIKER_JAREN_2                   533
#define TRAINER_FISHERMAN_ELLIOT_2              534
#define TRAINER_ROCKER_LUCA_2                   535
#define TRAINER_BEAUTY_SHEILA_2                 536
#define TRAINER_BIRD_KEEPER_ROBERT_2            537
#define TRAINER_BIRD_KEEPER_ROBERT_3            538
#define TRAINER_PICNICKER_SUSIE_2               539
#define TRAINER_PICNICKER_SUSIE_3               540
#define TRAINER_PICNICKER_SUSIE_4               541
#define TRAINER_BIKER_LUKAS_2                   542
#define TRAINER_BIRD_KEEPER_BENNY_2             543
#define TRAINER_BIRD_KEEPER_BENNY_3             544
#define TRAINER_BIRD_KEEPER_MARLON_2            545
#define TRAINER_BIRD_KEEPER_MARLON_3            546
#define TRAINER_BEAUTY_GRACE_2                  547
#define TRAINER_BIRD_KEEPER_CHESTER_2           548
#define TRAINER_BIRD_KEEPER_CHESTER_3           549
#define TRAINER_PICNICKER_BECKY_2               550
#define TRAINER_PICNICKER_BECKY_3               551
#define TRAINER_PICNICKER_BECKY_4               552
#define TRAINER_CRUSH_KIN_RON_MYA_2             553
#define TRAINER_CRUSH_KIN_RON_MYA_3             554
#define TRAINER_CRUSH_KIN_RON_MYA_4             555
#define TRAINER_BIKER_RUBEN_2                   556
#define TRAINER_CUE_BALL_CAMRON_2               557
#define TRAINER_BIKER_JAXON_2                   558
#define TRAINER_CUE_BALL_ISAIAH_2               559
#define TRAINER_CUE_BALL_COREY_2                560
#define TRAINER_BIRD_KEEPER_JACOB_2             561
#define TRAINER_BIRD_KEEPER_JACOB_3             562
#define TRAINER_SWIMMER_FEMALE_ALICE_2          563
#define TRAINER_SWIMMER_MALE_DARRIN_2           564
#define TRAINER_PICNICKER_MISSY_2               565
#define TRAINER_PICNICKER_MISSY_3               566
#define TRAINER_FISHERMAN_WADE_2                567
#define TRAINER_SWIMMER_MALE_JACK_2             568
#define TRAINER_SIS_AND_BRO_LIL_IAN_2           569
#define TRAINER_SIS_AND_BRO_LIL_IAN_3           570
#define TRAINER_SWIMMER_MALE_FINN_2             571
#define TRAINER_CRUSH_GIRL_SHARON_2             572
#define TRAINER_CRUSH_GIRL_SHARON_3             573
#define TRAINER_CRUSH_GIRL_TANYA_2              574
#define TRAINER_CRUSH_GIRL_TANYA_3              575
#define TRAINER_BLACK_BELT_SHEA_2               576
#define TRAINER_BLACK_BELT_SHEA_3               577
#define TRAINER_BLACK_BELT_HUGH_2               578
#define TRAINER_BLACK_BELT_HUGH_3               579
#define TRAINER_CRUSH_KIN_MIK_KIA_2             580
#define TRAINER_CRUSH_KIN_MIK_KIA_3             581
#define TRAINER_TUBER_AMIRA_2                   582
#define TRAINER_TWINS_JOY_MEG_2                 583
#define TRAINER_PAINTER_RAYNA_2                 584
#define TRAINER_YOUNGSTER_DESTIN_2              585
#define TRAINER_PKMN_BREEDER_ALIZE_2            586
#define TRAINER_YOUNG_COUPLE_GIA_JES_2          587
#define TRAINER_YOUNG_COUPLE_GIA_JES_3          588
#define TRAINER_BIRD_KEEPER_MILO_2              589
#define TRAINER_BIRD_KEEPER_CHAZ_2              590
#define TRAINER_BIRD_KEEPER_HAROLD_2            591
#define TRAINER_SWIMMER_FEMALE_NICOLE_2         592
#define TRAINER_PSYCHIC_JACLYN_2                593
#define TRAINER_SWIMMER_MALE_SAMIR_2            594
#define TRAINER_HIKER_EARL_2                    595
#define TRAINER_RUIN_MANIAC_LARRY_2             596
#define TRAINER_POKEMANIAC_HECTOR_2             597
#define TRAINER_PSYCHIC_DARIO_2                 598
#define TRAINER_PSYCHIC_RODETTE_2               599
#define TRAINER_JUGGLER_MASON_2                 600
#define TRAINER_PKMN_RANGER_NICOLAS_2           601
#define TRAINER_PKMN_RANGER_MADELINE_2          602
#define TRAINER_CRUSH_GIRL_CYNDY_2              603
#define TRAINER_TAMER_EVAN_2                    604
#define TRAINER_PKMN_RANGER_JACKSON_2           605
#define TRAINER_PKMN_RANGER_KATELYN_2           606
#define TRAINER_COOLTRAINER_LEROY_2             607
#define TRAINER_COOLTRAINER_MICHELLE_2          608
#define TRAINER_COOL_COUPLE_LEX_NYA_2           609
#define TRAINER_BUG_CATCHER_COLTON_2            610
#define TRAINER_BUG_CATCHER_COLTON_3            611
#define TRAINER_BUG_CATCHER_COLTON_4            612
#define TRAINER_SWIMMER_MALE_MATTHEW_2          613
#define TRAINER_SWIMMER_MALE_TONY_2             614
#define TRAINER_SWIMMER_FEMALE_MELISSA_2        615
#define TRAINER_ELITE_FOUR_LORELEI_2            616
#define TRAINER_ELITE_FOUR_BRUNO_2              617
#define TRAINER_ELITE_FOUR_AGATHA_2             618
#define TRAINER_ELITE_FOUR_LANCE_2              619
#define TRAINER_CHAMPION_REMATCH_SQUIRTLE       620
#define TRAINER_CHAMPION_REMATCH_BULBASAUR      621
#define TRAINER_CHAMPION_REMATCH_CHARMANDER     622
#define TRAINER_CUE_BALL_PAXTON                 623
#define TRAINER_RIVAL_INDIGO_CHIKORITA          624
#define TRAINER_RIVAL_INDIGO_CYNDAQUIL          625
#define TRAINER_RIVAL_INDIGO_TOTODILE           626
#define TRAINER_ROCKET_JESSIE                   627
#define TRAINER_ROCKET_JAMES                    628
#define TRAINER_ROCKET_JESSIE_2                 629
#define TRAINER_ROCKET_JAMES_2                  630
#endif

// NOTE: Because each Trainer uses a flag to determine when they are defeated, there is
//       only space for 9 more trainers before the KANTO_TRAINER_FLAG_BANK_SIZE=640 cap
//       (enforced by the STATIC_ASSERT in battle_setup.c; TRAINERS_COUNT_FRLG is now 631).
//       MAX_TRAINERS_COUNT_FRLG can be increased but will take up additional saveblock space

#define TRAINERS_COUNT_FRLG                      631
#define MAX_TRAINERS_COUNT_FRLG                  768

#endif  // GUARD_CONSTANTS_OPPONENTS_FRLG_H
