#!/usr/bin/env python3
"""Generate the build-time cut-tree / smashable-rock index table (issue #16).

Why this exists
---------------
Cleared obstacles used to persist as a list of {mapGroup, mapNum, localId} triples capped at
CLEARED_OBSTACLE_MAX = 104, with NO eviction: past 104 clears, new cut trees and smashed rocks
silently stopped persisting and regrew on every rezone. This repo has **297** such obstacles, so
that is not a theoretical ceiling a completionist might brush - it is reached less than half way
through the game.

One bit per obstacle costs 38 bytes for today's 297 against 313 bytes for the 104-entry list, so
the bitfield both removes the cap and gives SaveBlock3 back ~350 bytes.

The stability problem, and the guard
------------------------------------
A build-time index is derived from the map data, so ADDING OR REMOVING an obstacle anywhere
renumbers every obstacle after it. In a shipped game the maps are frozen and that never happens;
in an actively-edited hack it happens routinely, and a renumber would silently re-point a saved
bit at a different tree - some regrow, others are pre-cleared, with nothing to say why.

So the generated table carries a HASH of itself. The save stores the hash it was written under,
and a mismatch clears the bits and re-stamps: every obstacle regrows exactly once after a map
edit, which is a visible, self-healing, understood outcome rather than silent corruption.

Usage (see the `obstacles` make target):
    python3 Testing/GenObstacleTable.py            # writes both headers, prints a summary
    python3 Testing/GenObstacleTable.py --check     # exit 1 if the committed headers are stale

Both outputs are COMMITTED, not build artifacts: the table is save-layout-affecting data and
belongs in review, and --check (wired into `make validate`) is what catches drift.
"""
import json, os, sys, glob, hashlib

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Must match IsObstacleGraphicsId() in src/event_object_movement.c.
OBSTACLE_GFX = {
    "OBJ_EVENT_GFX_CUTTABLE_TREE",
    "OBJ_EVENT_GFX_CUTTABLE_TREE_FRLG",
    "OBJ_EVENT_GFX_BREAKABLE_ROCK",
    "OBJ_EVENT_GFX_BREAKABLE_ROCK_FRLG",
}

# Bits reserved in the save. Sized well above today's count so ordinary map work does not force a
# save-format bump - only exceeding this does. 512 bits = 64 bytes.
OBSTACLE_SLOTS = 512

CONST_HEADER = os.path.join(ROOT, "include", "constants", "cleared_obstacles.h")
DATA_HEADER = os.path.join(ROOT, "src", "data", "cleared_obstacles.h")


def collect():
    """-> sorted list of (mapGroup, mapNum, localId, mapName) for every obstacle in the game."""
    groups = json.load(open(os.path.join(ROOT, "data/maps/map_groups.json"), encoding="utf-8"))
    order = groups["group_order"]

    # map name (e.g. "PetalburgCity") -> (groupIndex, mapIndex)
    where = {}
    for gi, gname in enumerate(order):
        for mi, mapname in enumerate(groups[gname]):
            where[mapname] = (gi, mi)

    out = []
    missing = []
    for path in sorted(glob.glob(os.path.join(ROOT, "data/maps/*/map.json"))):
        d = json.load(open(path, encoding="utf-8"))
        name = d.get("name")
        events = d.get("object_events", [])
        hits = [(i + 1, o) for i, o in enumerate(events) if o.get("graphics_id") in OBSTACLE_GFX]
        if not hits:
            continue
        if name not in where:
            # A map with obstacles that is not in any group would be silently unreachable by this
            # table, so refuse rather than emit a table that quietly omits it.
            missing.append((name, os.path.basename(os.path.dirname(path)), len(hits)))
            continue
        gi, mi = where[name]
        for local_id, _o in hits:
            out.append((gi, mi, local_id, name))

    if missing:
        for name, d, n in missing:
            print(f"ERROR: map '{name}' (data/maps/{d}) has {n} obstacle(s) but is in no map group",
                  file=sys.stderr)
        sys.exit(1)

    out.sort(key=lambda t: (t[0], t[1], t[2]))
    return out


def key_of(entry):
    g, m, l, _ = entry
    return (g << 16) | (m << 8) | l


def render(entries):
    keys = [key_of(e) for e in entries]
    if len(set(keys)) != len(keys):
        sys.exit("ERROR: duplicate (mapGroup, mapNum, localId) key — the table must be a set")
    if len(keys) > OBSTACLE_SLOTS:
        sys.exit(f"ERROR: {len(keys)} obstacles exceeds OBSTACLE_SLOTS={OBSTACLE_SLOTS}. "
                 f"Raising it changes sizeof(struct RegionSave) — bump SAVE_FORMAT_VERSION "
                 f"and add a migration ladder step.")

    digest = hashlib.sha256(b",".join(b"%d" % k for k in keys)).hexdigest()
    table_hash = int(digest[:8], 16)

    const = f"""#ifndef GUARD_CONSTANTS_CLEARED_OBSTACLES_H
#define GUARD_CONSTANTS_CLEARED_OBSTACLES_H

// AUTO-GENERATED by Testing/GenObstacleTable.py from data/maps/*/map.json — do not edit by hand.
// Regenerate with `make obstacles`; `make validate` fails if this is stale.
//
// One save bit per cut tree / smashable rock in the game. Replaces the old 104-entry
// {{mapGroup, mapNum, localId}} list, which had no eviction: past 104 clears, obstacles silently
// stopped persisting and regrew on every rezone. There are {len(keys)} obstacles, so that cap was
// reached well before the end of a single playthrough.

#define CLEARED_OBSTACLE_COUNT      {len(keys)}   // obstacles present in the map data today
#define CLEARED_OBSTACLE_SLOTS      {OBSTACLE_SLOTS}   // bits reserved in the save (save-layout affecting)
#define CLEARED_OBSTACLE_BYTES      (CLEARED_OBSTACLE_SLOTS / 8)

// Identity of the generated table. A map edit that adds or removes an obstacle renumbers every
// index after it, which would silently re-point saved bits at different obstacles. The save
// stores the hash it was written under; on a mismatch the bits are cleared and re-stamped, so
// every obstacle regrows exactly ONCE after a map edit instead of drifting invisibly.
#define CLEARED_OBSTACLE_TABLE_HASH 0x{table_hash:08X}

#endif // GUARD_CONSTANTS_CLEARED_OBSTACLES_H
"""

    rows = []
    last_map = None
    for e in entries:
        g, m, l, name = e
        if name != last_map:
            rows.append(f"    // {name}")
            last_map = name
        rows.append(f"    0x{key_of(e):06X}, // group {g}, map {m}, localId {l}")

    data = f"""// AUTO-GENERATED by Testing/GenObstacleTable.py from data/maps/*/map.json — do not edit by hand.
// Regenerate with `make obstacles`; `make validate` fails if this is stale.
//
// Sorted ascending so ObstacleIndex() can binary-search it. Key = (mapGroup << 16) | (mapNum << 8)
// | localId. The array index IS the save bit index, which is why the order must never be
// hand-shuffled — see CLEARED_OBSTACLE_TABLE_HASH.
static const u32 sClearedObstacleKeys[CLEARED_OBSTACLE_COUNT] =
{{
{chr(10).join(rows)}
}};
"""
    return const, data, table_hash


def main():
    check = "--check" in sys.argv
    entries = collect()
    const, data, table_hash = render(entries)

    if check:
        stale = []
        for path, want in ((CONST_HEADER, const), (DATA_HEADER, data)):
            try:
                have = open(path, encoding="utf-8").read()
            except OSError:
                stale.append(path + " (missing)")
                continue
            if have != want:
                stale.append(path)
        if stale:
            print("FAIL — the committed obstacle table is stale vs data/maps/:")
            for s in stale:
                print("  " + s)
            print("  Run `make obstacles` and commit the result. NOTE: if the obstacle SET changed,")
            print("  CLEARED_OBSTACLE_TABLE_HASH changes too, and every existing save's obstacles")
            print("  regrow once on next load. That is intended and self-healing.")
            return 1
        print(f"OK — obstacle table current: {len(entries)} obstacles, hash 0x{table_hash:08X}")
        return 0

    os.makedirs(os.path.dirname(CONST_HEADER), exist_ok=True)
    open(CONST_HEADER, "w", encoding="utf-8").write(const)
    open(DATA_HEADER, "w", encoding="utf-8").write(data)
    print(f"wrote {os.path.relpath(CONST_HEADER, ROOT)} and {os.path.relpath(DATA_HEADER, ROOT)}")
    print(f"  {len(entries)} obstacles across {len({(e[0], e[1]) for e in entries})} maps, "
          f"{OBSTACLE_SLOTS} slots reserved, hash 0x{table_hash:08X}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
