package.path=assert(os.getenv('PW_FEATURE_LIB'))..'/?.lua;'..package.path
local F,S,U,X,tap,hook,close,tasks,windows=require('swsh_helpers')('SwShTransfer')
F.run(function()
 assert(F.boot(100));hook(0)
 F.check('six party members before deposit',F.r8(S.gPartiesCount)==6)
 hook(4);tap('Down');tap('A');F.check('deposit screen opened',F.r32(U.sStorage)~=0);F.shot('deposit')
 tap('A',2);F.shot('deposit_box_choice');tap('A',1,240);F.shot('deposit_result');close('deposit')
 F.check('deposit removes one party member',F.r8(S.gPartiesCount)==5,'party='..F.r8(S.gPartiesCount))
 hook(4);tap('Down',2);tap('A');F.check('withdraw screen opened',F.r32(U.sStorage)~=0);F.shot('withdraw')
 tap('A',2,240);F.shot('withdraw_result');close('withdraw')
 F.check('withdraw restores six party members',F.r8(S.gPartiesCount)==6,'party='..F.r8(S.gPartiesCount))
 -- Move an item through normal swap controls and inspect the stored order afterward.
 hook(0);hook(1,0)
 local pocket=F.r32(S.gBagPockets);local second=F.r16(pocket+4)
 tap('Select');tap('Down');tap('A');F.shot('bag_reordered')
 F.check('swap returns control to Bag',tasks(U.Task_BagMenu_HandleInput)==1);close('swap')
 F.check('swap changes first item to previous second',F.r16(F.r32(S.gBagPockets))==second)
 F.finish()
end)
