package.path=assert(os.getenv('PW_FEATURE_LIB'))..'/?.lua;'..package.path
local F,S,U,X,tap,hook=require('bw_helpers')('BattlePaletteSave')
F.run(function()
 assert(F.boot(100));hook(202,0);hook(200,0,480);hook(9,0,1200)
 F.check('prepared Ice Path save written',F.r16(X.gSpecialVar_0x8005)==1)
 local group,map=F.grp(),F.mapn()
 client.reboot_core();F.idle(5);F.check('prepared save reloads',F.boot(group))
 F.check('Ice Path location persisted',F.mapn()==map)
 F.check('prepared party persisted',F.r8(S.gPartiesCount)==6)
 F.check('normal walking works',F.step('Up'));F.shot('prepared_ice_path');F.finish()
end)
