#!/usr/bin/env python3
"""Reproduce the regional lighting assets from the documented baseline checkout."""
import argparse
import json
from pathlib import Path
import re
import struct
import shutil

from assets import Assets


def write_palette(path, colors):
    assert len(colors) == 16
    path.write_text('JASC-PAL\n0100\n16\n'+''.join('%d %d %d\n' % c for c in colors))


def warm(rgb):
    brightness = sum(rgb)//3
    return (248, 232, 160) if brightness >= 190 else ((248, 200, 104) if brightness >= 140 else (216, 152, 64))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--base', type=Path, required=True)
    parser.add_argument('--out', type=Path, required=True)
    args = parser.parse_args()
    assert args.base.resolve() != args.out.resolve(), 'Use a separate, unchanged baseline checkout'
    # Reset only files previously generated by the companion placement pass.
    for filename in ('lamps.json','fallarbor_glass.json'):
        manifest = args.out/'Testing/night-lighting'/filename
        if manifest.exists():
            for relative in json.loads(manifest.read_text())['modified_paths']:
                source = args.base/relative
                if source.is_file():
                    shutil.copyfile(source,args.out/relative)
    a = Assets(args.base)
    root = args.out
    for layout in a.towns.values():
        shutil.copyfile(args.base/layout['blockdata_filepath'], root/layout['blockdata_filepath'])
    spec = json.loads(Path(__file__).with_name('primary_windows.json').read_text())
    header = a.headers
    meta_header = (args.base/'src/data/tilesets/metatiles.h').read_text()
    externs = (args.base/'include/tilesets.h').read_text()
    doors = (args.base/'src/field_door.c').read_text()
    layout_document = json.loads((args.base/'data/layouts/layouts.json').read_text())
    report = {'primary_variants': {}, 'palettes': {}, 'layouts': []}
    for primary, authored in spec.items():
        is_hoenn = primary == 'gTileset_General'
        split, bank = (512, 12) if is_hoenn else (640, 7)
        ps = 6 if is_hoenn else 7
        variant = primary+'Night'
        s = a.sets[primary]
        layout = next(l for l in a.towns.values() if l['primary_tileset'] == primary)
        # A pattern is the original tile/palette pair plus its authored glass entries.
        patterns = {}
        colors = set()
        for mid, cells in authored.items():
            for k, flags in cells.items():
                word = s['meta'][int(mid)][int(k)]
                key = word & 0xF3FF
                flags = set(flags)
                assert key not in patterns or patterns[key] == flags
                patterns[key] = flags
                tile, pal, _ = a.tile(layout, word)
                colors.update((pal[c], c in flags) for c in tile.get_flattened_data() if c)
        colors = sorted(colors)
        assert len(colors) <= 15, (primary, len(colors))
        palette = [(0,0,0)]+[c for c, lit in colors]+[(0,0,0)]*(15-len(colors))
        masks = [i+1 for i, (c, lit) in enumerate(colors) if lit]
        color_index = {key: i+1 for i, key in enumerate(colors)}
        secondary_names = {l['secondary_tileset'] for l in a.layouts.values()
                           if l['primary_tileset'] == primary and l['secondary_tileset'] in a.sets}
        # Exclude destinations overwritten by existing water/flower animation DMA.
        animated = set(range(432,462)) | set(range(464,474)) | set(range(480,490)) | set(range(496,502)) | set(range(508,512)) if is_hoenn else set(range(416,482)) | set(range(508,512))
        used = {v & 1023 for name in secondary_names | {primary}
                for row in a.sets[name]['meta'] for v in row}
        free = [i for i in range(1, split) if i not in used and i not in animated]
        sheet = s['image'].copy()
        replacements = {}
        allocations = []
        for word, flags in sorted(patterns.items()):
            assert free, primary
            target = free.pop(0)
            tile, pal, _ = a.tile(layout, word)
            tile.putdata([color_index[pal[c], c in flags] if c else 0 for c in tile.get_flattened_data()])
            sheet.paste(tile, (target % 16*8, target//16*8))
            replacements[word] = (bank << 12) | target
            allocations.append({'source': word, 'target': target, 'glass': sorted(flags)})
        folder = root/s['folder'].relative_to(args.base)
        sheet.save(folder/'tiles.png', optimize=True)
        variant_path = folder/'night_metatiles.bin'
        def replace(rows):
            return [tuple(replacements.get(v & 0xF3FF, v & 0xF3FF) | (v & 0xC00) for v in row) for row in rows]
        variant_path.write_bytes(b''.join(struct.pack('<8H', *row) for row in replace(s['meta'])))
        meta_symbol = re.search(r'TILESET_METATILES\((\w+),', s['body'])[1]
        meta_header += '\nconst u16 '+meta_symbol+'Night[] = INCBIN_U16("'+str(variant_path.relative_to(root))+'");\n'
        variant_body = s['body'].replace(meta_symbol+',', meta_symbol+'Night,')
        original = 'const struct Tileset '+primary+' =\n{'+s['body']+'};'
        assert original in header
        header = header.replace(original, original+'\n\n// Shared windows use the paired outdoor tileset\'s dedicated lighting palette.\nconst struct Tileset '+variant+' =\n{'+variant_body+'};')
        externs = externs.replace('extern const struct Tileset '+primary+';', 'extern const struct Tileset '+primary+';\nextern const struct Tileset '+variant+';')
        # Door lookup keys include the tileset pointer. Reuse the exact original frames.
        for line in list(doors.splitlines()):
            if '&'+primary+',' in line:
                doors = doors.replace(line, line+'\n'+line.replace('&'+primary+',', '&'+variant+','))
        compatible = set()
        for name in sorted(secondary_names):
            secondary = a.sets[name]
            if any(v >> 12 == bank and v & 1023 for row in secondary['meta'] for v in row):
                continue
            # Only outdoor families participate, including every main town's family.
            if not any(l['secondary_tileset'] == name for l in a.towns.values()):
                continue
            compatible.add(name)
            dest = root/secondary['folder'].relative_to(args.base)
            write_palette(dest/f'palettes/{bank:02}.pal', palette)
            alternate = [warm(c) if i in masks else c for i,c in enumerate(palette)]
            alt = (bank+9)%16
            write_palette(dest/f'palettes/{alt:02}.pal', alternate)
            for slot in [bank, alt]:
                (dest/f'palettes/{slot:02}.pla').write_text(''.join(f'{i}\n' for i in masks))
            shared_primaries = {l['primary_tileset'] for l in a.layouts.values() if l['secondary_tileset'] == name}
            rows = replace(secondary['meta']) if shared_primaries == {primary} else secondary['meta']
            (root/secondary['meta_path'].relative_to(args.base)).write_bytes(b''.join(struct.pack('<8H', *row) for row in rows))
            body = secondary['body']
            assert '.swapPalettes' not in body
            header = header.replace('const struct Tileset '+name+' =\n{'+body+'};', 'const struct Tileset '+name+' =\n{'+body.replace('    .isSecondary = TRUE,', '    .isSecondary = TRUE,\n    .swapPalettes = (1 << '+str(bank-ps)+'),')+'};')
            report['palettes'][name] = {'bank': bank, 'alternate': alt, 'glass': masks}
        for l in layout_document['layouts']:
            if l['primary_tileset'] == primary and l['secondary_tileset'] in compatible and l['layout_version'] == ('emerald' if is_hoenn else 'frlg'):
                l['primary_tileset'] = variant
                report['layouts'].append(l['name'])
        report['primary_variants'][variant] = {'original': primary, 'allocations': allocations, 'colors': colors}
    # These locally authored entries are glass; roofs, water, grass, and
    # differently colored decorative panels deliberately keep normal tinting.
    local = json.loads(Path(__file__).with_name('local_glass.json').read_text())
    report['local_glass'] = local
    for name, banks in local.items():
        source = a.sets[name]
        layout = next(l for l in a.towns.values() if l['secondary_tileset'] == name)
        _, ps = a.split(layout)
        bits = []
        dest = root/source['folder'].relative_to(args.base)
        for bank_text, flags in banks.items():
            bank = int(bank_text)
            alternate = (bank+9)%16
            assert alternate < ps or alternate >= 13
            write_palette(dest/f'palettes/{bank:02}.pal', source['palettes'][bank])
            palette = list(source['palettes'][bank])
            all_flags = sorted(set(flags) | source['masks'].get(bank,set()))
            for i in flags:
                palette[i] = warm(palette[i])
            write_palette(dest/f'palettes/{alternate:02}.pal', palette)
            for slot in [bank, alternate]:
                (dest/f'palettes/{slot:02}.pla').write_text(''.join(f'{i}\n' for i in all_flags))
            bits.append(bank-ps)
        pattern = r'(const struct Tileset '+re.escape(name)+r'\s*=\s*\{)(.*?)(\};)'
        def add_local_bits(match):
            body = match[2]
            extra = ' | '.join(f'(1 << {bit})' for bit in bits)
            if '.swapPalettes' in body:
                body = re.sub(r'(\.swapPalettes\s*=\s*)([^,]+)', lambda m: m[1]+m[2]+' | '+extra, body)
            else:
                body = body.replace('    .isSecondary = TRUE,', '    .isSecondary = TRUE,\n    .swapPalettes = '+extra+',')
            return match[1]+body+match[3]
        header, count = re.subn(pattern, add_local_bits, header, count=1, flags=re.S)
        assert count == 1
    # Extend the approved amber treatment to Johto's shared glass and local
    # cool-colored glass. Existing gold/red lantern ramps keep their identity.
    johto = {name for l in a.towns.values() if l['layout_version'] == 'johto'
             for name in (l['primary_tileset'], l['secondary_tileset'])}
    report['johto_glass'] = {}
    for name in sorted(johto):
        source = a.sets[name]
        primary = '.isSecondary = FALSE' in source['body']
        bits = []
        for bank, flags in source['masks'].items():
            if bank >= 13 or (primary and bank >= 7) or (not primary and bank < 7):
                continue
            selected = [i for i in flags if source['palettes'][bank][i][2] > source['palettes'][bank][i][0]]
            if not selected:
                continue
            # Preserve #335's exact three-entry pilot ramp.
            if name in ('gTileset_NewBarkTown', 'gTileset_CherrygroveCity') and bank == 8:
                continue
            alternate = (bank+9)%16
            assert (primary and alternate >= 7) or (not primary and alternate < 7)
            palette = list(source['palettes'][bank])
            for i in selected:
                palette[i] = warm(palette[i])
            dest = root/source['folder'].relative_to(args.base)
            write_palette(dest/f'palettes/{alternate:02}.pal', palette)
            (dest/f'palettes/{alternate:02}.pla').write_text(''.join(f'{i}\n' for i in sorted(flags)))
            bits.append(bank if primary else bank-7)
            report['johto_glass'].setdefault(name, {})[bank] = selected
        if bits:
            pattern = r'(const struct Tileset '+re.escape(name)+r'\s*=\s*\{)(.*?)(\};)'
            def add_bits(match):
                body = match[2]
                extra = ' | '.join(f'(1 << {bit})' for bit in bits)
                if '.swapPalettes' in body:
                    body = re.sub(r'(\.swapPalettes\s*=\s*)([^,]+)', lambda m: m[1]+m[2]+' | '+extra, body)
                else:
                    body = body.replace('    .isCompressed = TRUE,', '    .isCompressed = TRUE,\n    .swapPalettes = '+extra+',')
                return match[1]+body+match[3]
            header, count = re.subn(pattern, add_bits, header, count=1, flags=re.S)
            assert count == 1
    (root/'src/data/tilesets/headers.h').write_text(header)
    (root/'src/data/tilesets/metatiles.h').write_text(meta_header)
    (root/'include/tilesets.h').write_text(externs)
    (root/'src/field_door.c').write_text(doors)
    # Preserve the repository's formatting; only change the selected symbol strings.
    original_layouts = (args.base/'data/layouts/layouts.json').read_text()
    for before, after in zip(a.layouts.values(), layout_document['layouts']):
        if before['primary_tileset'] != after['primary_tileset']:
            pattern = r'("id": "'+re.escape(before['id'])+r'",.*?"primary_tileset": ")'+re.escape(before['primary_tileset'])+'"'
            original_layouts, count = re.subn(pattern, lambda m: m[1]+after['primary_tileset']+'"', original_layouts, count=1, flags=re.S)
            assert count == 1
    (root/'data/layouts/layouts.json').write_text(original_layouts)
    (root/'Testing/night-lighting/authoring.json').write_text(json.dumps(report, indent=2)+'\n')
    print(f'Authored {len(report["palettes"])} outdoor palettes and {len(report["layouts"])} shared layouts.')


if __name__ == '__main__':
    main()
