#include "global.h"
#include "battle.h"
#include "clear_save_data_menu.h"
#include "decompress.h"
#include "event_data.h"
#include "gba/m4a_internal.h"
#include "gpu_regs.h"
#include "graphics.h"
#include "intro.h"
#include "m4a.h"
#include "main.h"
#include "main_menu.h"
#include "palette.h"
#include "quickstart.h"
#include "reset_rtc_screen.h"
#include "scanline_effect.h"
#include "sound.h"
#include "sprite.h"
#include "task.h"
#include "title_screen.h"
#include "constants/rgb.h"
#include "constants/songs.h"

#if ALL_REGIONS

// Generated by tools/export-world-title.mjs. BG0 and BG2 share
// the 8bpp artwork tiles; the original 4bpp fog occupies the remaining char area.
#define FOG_VRAM_OFFSET 0xD800
#define FOG_SCREEN_BLOCK 29
#define SCENERY_SCREEN_BLOCK 30
#define LOGO_SCREEN_BLOCK 31
#define TAG_WORLD_PRESS_START 1001
#define CLEAR_SAVE_COMBO (B_BUTTON | SELECT_BUTTON | DPAD_UP)
#define RESET_RTC_COMBO (B_BUTTON | SELECT_BUTTON | DPAD_LEFT)

static const u32 sWorldTitleTiles[] = INCBIN_U32("graphics/title_screen/world/background_tiles.bin");
static const u16 sWorldTitlePalette[] = INCBIN_U16("graphics/title_screen/world/palette.bin");
static const u16 sWorldSceneryMap[] = INCBIN_U16("graphics/title_screen/world/background_map.bin");
static const u16 sWorldLogoMap[] = INCBIN_U16("graphics/title_screen/world/logo_map.bin");
static const u32 sWorldFogTiles[] = INCBIN_U32("graphics/title_screen/world/fog_tiles.bin");
static const u16 sWorldFogMap[] = INCBIN_U16("graphics/title_screen/world/fog_map.bin");

STATIC_ASSERT(sizeof(sWorldTitleTiles) <= FOG_VRAM_OFFSET, WorldTitleTilesFit);
STATIC_ASSERT(FOG_VRAM_OFFSET + sizeof(sWorldFogTiles) <= FOG_SCREEN_BLOCK * 0x800, WorldFogTilesFit);
STATIC_ASSERT(sizeof(sWorldTitlePalette) == BG_PLTT_SIZE, WorldTitlePaletteSize);
STATIC_ASSERT(sizeof(sWorldSceneryMap) == 0x800, WorldSceneryMapSize);
STATIC_ASSERT(sizeof(sWorldLogoMap) == 0x800, WorldLogoMapSize);
STATIC_ASSERT(sizeof(sWorldFogMap) == 0x800, WorldFogMapSize);

static void MainCB2_WorldTitleScreen(void);
static void Task_WorldTitleScreen(u8 taskId);
static void SpriteCB_WorldPressStart(struct Sprite *sprite);
static void CB2_LeaveWorldTitleScreen(void);

static EWRAM_DATA MainCallback sWorldTitleNextCallback = NULL;

static const struct OamData sPressStartOam =
{
    .shape = SPRITE_SHAPE(32x8),
    .size = SPRITE_SIZE(32x8),
    .bpp = ST_OAM_4BPP,
    .priority = 0,
};

// The source's 160px row is centered, including its transparent side padding.
// Starting at tile 1 skips 8px and shifts the visible prompt left of the logo.
static const union AnimCmd sPressStart0[] = { ANIMCMD_FRAME(0, 4), ANIMCMD_END };
static const union AnimCmd sPressStart1[] = { ANIMCMD_FRAME(4, 4), ANIMCMD_END };
static const union AnimCmd sPressStart2[] = { ANIMCMD_FRAME(8, 4), ANIMCMD_END };
static const union AnimCmd sPressStart3[] = { ANIMCMD_FRAME(12, 4), ANIMCMD_END };
static const union AnimCmd sPressStart4[] = { ANIMCMD_FRAME(16, 4), ANIMCMD_END };
static const union AnimCmd *const sPressStartAnims[] =
{
    sPressStart0, sPressStart1, sPressStart2, sPressStart3, sPressStart4,
};

static const struct SpriteTemplate sPressStartTemplate =
{
    .tileTag = TAG_WORLD_PRESS_START,
    .paletteTag = TAG_WORLD_PRESS_START,
    .oam = &sPressStartOam,
    .anims = sPressStartAnims,
    .affineAnims = gDummySpriteAffineAnimTable,
    .callback = SpriteCB_WorldPressStart,
};
static const struct CompressedSpriteSheet sPressStartSheet =
{
    .data = gTitleScreenPressStartGfx,
    .size = 0x520,
    .tag = TAG_WORLD_PRESS_START,
};
static const struct SpritePalette sPressStartPalette =
{
    .data = gTitleScreenPressStartPal,
    .tag = TAG_WORLD_PRESS_START,
};

static void SpriteCB_WorldPressStart(struct Sprite *sprite)
{
    sprite->data[0] = (sprite->data[0] + 1) & 63;
    sprite->invisible = sprite->data[0] >= 48;
}

static void VBlankCB_WorldTitleScreen(void)
{
    ScanlineEffect_InitHBlankDmaTransfer();
    LoadOam();
    ProcessSpriteCopyRequests();
    TransferPlttBuffer();
    SetGpuReg(REG_OFFSET_BG1VOFS, gBattle_BG1_Y);
}

void CB2_InitWorldTitleScreen(void)
{
    u32 i;

    switch (gMain.state)
    {
    case 0:
        SetVBlankCallback(NULL);
        SetHBlankCallback(NULL);
        ScanlineEffect_Stop();
        ScanlineEffect_Clear();
        SetGpuReg(REG_OFFSET_DISPCNT, DISPCNT_FORCED_BLANK);
        for (i = REG_OFFSET_BG0CNT; i <= REG_OFFSET_BG3VOFS; i += 2)
            SetGpuReg(i, 0);
        SetGpuReg(REG_OFFSET_WIN0H, 0);
        SetGpuReg(REG_OFFSET_WIN0V, 0);
        SetGpuReg(REG_OFFSET_WIN1H, 0);
        SetGpuReg(REG_OFFSET_WIN1V, 0);
        SetGpuReg(REG_OFFSET_WININ, 0);
        SetGpuReg(REG_OFFSET_WINOUT, 0);
        SetGpuReg(REG_OFFSET_MOSAIC, 0);
        SetGpuReg(REG_OFFSET_BLDCNT, 0);
        SetGpuReg(REG_OFFSET_BLDALPHA, 0);
        SetGpuReg(REG_OFFSET_BLDY, 0);
        DmaFill16(3, 0, (void *)VRAM, VRAM_SIZE);
        DmaFill32(3, 0, (void *)OAM, OAM_SIZE);
        DmaFill16(3, 0, (void *)PLTT, PLTT_SIZE);
        ResetPaletteFade();
        ResetTasks();
        ResetSpriteData();
        FreeAllSpritePalettes();
        gReservedSpritePaletteCount = 0;
        gBattle_BG1_X = 0;
        gBattle_BG1_Y = 0;
        sWorldTitleNextCallback = NULL;
        gMain.state++;
        break;
    case 1:
        DmaCopy32(3, sWorldTitleTiles, (void *)VRAM, sizeof(sWorldTitleTiles));
        DmaCopy32(3, sWorldFogTiles, (void *)(VRAM + FOG_VRAM_OFFSET), sizeof(sWorldFogTiles));
        DmaCopy16(3, sWorldSceneryMap, (void *)BG_SCREEN_ADDR(SCENERY_SCREEN_BLOCK), sizeof(sWorldSceneryMap));
        DmaCopy16(3, sWorldLogoMap, (void *)BG_SCREEN_ADDR(LOGO_SCREEN_BLOCK), sizeof(sWorldLogoMap));
        DmaCopy16(3, sWorldFogMap, (void *)BG_SCREEN_ADDR(FOG_SCREEN_BLOCK), sizeof(sWorldFogMap));
        LoadPalette(sWorldTitlePalette, 0, sizeof(sWorldTitlePalette));
        LoadCompressedSpriteSheet(&sPressStartSheet);
        LoadSpritePalette(&sPressStartPalette);
        for (i = 0; i < ARRAY_COUNT(sPressStartAnims); i++)
        {
            u8 spriteId = CreateSprite(&sPressStartTemplate, DISPLAY_WIDTH / 2 - 64 + i * 32, 146, 0);
            StartSpriteAnim(&gSprites[spriteId], i);
        }
        if (QUICKSTART && QUICKSTART_HUD)
            CreateQuickstartHud();
        BuildOamBuffer();
        gMain.state++;
        break;
    default:
        SetGpuReg(REG_OFFSET_BG0CNT, BGCNT_PRIORITY(2) | BGCNT_CHARBASE(0) | BGCNT_SCREENBASE(SCENERY_SCREEN_BLOCK) | BGCNT_256COLOR | BGCNT_TXT256x256);
        SetGpuReg(REG_OFFSET_BG1CNT, BGCNT_PRIORITY(1) | BGCNT_CHARBASE(3) | BGCNT_SCREENBASE(FOG_SCREEN_BLOCK) | BGCNT_16COLOR | BGCNT_TXT256x256);
        SetGpuReg(REG_OFFSET_BG2CNT, BGCNT_PRIORITY(0) | BGCNT_CHARBASE(0) | BGCNT_SCREENBASE(LOGO_SCREEN_BLOCK) | BGCNT_256COLOR | BGCNT_TXT256x256);
        SetGpuReg(REG_OFFSET_BLDCNT, BLDCNT_TGT1_BG1 | BLDCNT_EFFECT_BLEND | BLDCNT_TGT2_BG0 | BLDCNT_TGT2_BD);
        SetGpuReg(REG_OFFSET_BLDALPHA, BLDALPHA_BLEND(6, 15));
        CreateTask(Task_WorldTitleScreen, 0);
        ScanlineEffect_InitWave(0, DISPLAY_HEIGHT, 4, 4, 0, SCANLINE_EFFECT_REG_BG1HOFS, TRUE);
        BeginNormalPaletteFade(PALETTES_ALL, 1, 16, 0, RGB_WHITEALPHA);
        SetVBlankCallback(VBlankCB_WorldTitleScreen);
        EnableInterrupts(INTR_FLAG_VBLANK);
        SetGpuReg(REG_OFFSET_DISPCNT, DISPCNT_MODE_0 | DISPCNT_OBJ_1D_MAP | DISPCNT_BG0_ON | DISPCNT_BG1_ON | DISPCNT_BG2_ON | DISPCNT_OBJ_ON);
        m4aSongNumStart(MUS_TITLE);
        SetMainCallback2(MainCB2_WorldTitleScreen);
        break;
    }
}

static void MainCB2_WorldTitleScreen(void)
{
    RunTasks();
    AnimateSprites();
    BuildOamBuffer();
    UpdatePaletteFade();
}

static void LeaveWorldTitleScreen(MainCallback nextCallback, u16 fadeColor)
{
    // Stop HBlank DMA before another screen reuses these backgrounds and tasks.
    ScanlineEffect_Stop();
    SetGpuReg(REG_OFFSET_BG1HOFS, 0);
    FadeOutBGM(4);
    BeginNormalPaletteFade(PALETTES_ALL, 0, 0, 16, fadeColor);
    sWorldTitleNextCallback = nextCallback;
    SetMainCallback2(CB2_LeaveWorldTitleScreen);
}

static void CB2_LeaveWorldTitleScreen(void)
{
    if (!UpdatePaletteFade())
        SetMainCallback2(sWorldTitleNextCallback);
}

static void Task_WorldTitleScreen(u8 taskId)
{
    // One pixel per four frames, with a bounded counter for an exact 256px wrap.
    gTasks[taskId].data[0] = (gTasks[taskId].data[0] + 1) & 1023;
    gBattle_BG1_Y = gTasks[taskId].data[0] / 4;
    if (gPaletteFade.active)
        return;

    // Check held service chords before SELECT's development quickstart shortcut.
    if (JOY_HELD(CLEAR_SAVE_COMBO) == CLEAR_SAVE_COMBO)
        LeaveWorldTitleScreen(CB2_InitClearSaveDataScreen, RGB_WHITEALPHA);
    else if (JOY_HELD(RESET_RTC_COMBO) == RESET_RTC_COMBO)
    {
        if (CanResetRTC())
            LeaveWorldTitleScreen(CB2_InitResetRtcScreen, RGB_BLACK);
    }
    else if (JOY_NEW(A_BUTTON | START_BUTTON))
        LeaveWorldTitleScreen(CB2_InitMainMenu, RGB_WHITEALPHA);
    else if (QUICKSTART && JOY_NEW(SELECT_BUTTON))
    {
        ScanlineEffect_Stop();
        Quickstart();
    }
    else if ((gMPlayInfo_BGM.status & 0xFFFF) == 0)
        LeaveWorldTitleScreen(CB2_InitCopyrightScreenAfterTitleScreen, RGB_WHITEALPHA);
}

#endif // ALL_REGIONS
