// AUTO-GENERATED by Testing/GenObstacleTable.py from data/maps/*/map.json — do not edit by hand.
// Regenerate with `make obstacles`; `make validate` fails if this is stale.
//
// Sorted ascending so ObstacleIndex() can binary-search it. Key = (mapGroup << 16) | (mapNum << 8)
// | localId. The array index IS the save bit index, which is why the order must never be
// hand-shuffled — see CLEARED_OBSTACLE_TABLE_HASH.
static const u32 sClearedObstacleKeys[CLEARED_OBSTACLE_COUNT] =
{
    // Route103
    0x00120E, // group 0, map 18, localId 14
    0x00120F, // group 0, map 18, localId 15
    // Route104
    0x00131E, // group 0, map 19, localId 30
    // Route111
    0x001A0F, // group 0, map 26, localId 15
    0x001A10, // group 0, map 26, localId 16
    0x001A1B, // group 0, map 26, localId 27
    // Route114
    0x001D0B, // group 0, map 29, localId 11
    0x001D12, // group 0, map 29, localId 18
    0x001D13, // group 0, map 29, localId 19
    0x001D14, // group 0, map 29, localId 20
    0x001D15, // group 0, map 29, localId 21
    // Route115
    0x001E0F, // group 0, map 30, localId 15
    // Route116
    0x001F04, // group 0, map 31, localId 4
    0x001F05, // group 0, map 31, localId 5
    0x001F0C, // group 0, map 31, localId 12
    0x001F0E, // group 0, map 31, localId 14
    0x001F1A, // group 0, map 31, localId 26
    // Route117
    0x00200F, // group 0, map 32, localId 15
    // Route118
    0x00210C, // group 0, map 33, localId 12
    // Route120
    0x002315, // group 0, map 35, localId 21
    0x002320, // group 0, map 35, localId 32
    0x002321, // group 0, map 35, localId 33
    // Route121
    0x00240F, // group 0, map 36, localId 15
    0x002410, // group 0, map 36, localId 16
    0x002416, // group 0, map 36, localId 22
    // Route123
    0x002612, // group 0, map 38, localId 18
    0x002613, // group 0, map 38, localId 19
    0x002614, // group 0, map 38, localId 20
    // RusturfTunnel
    0x180402, // group 24, map 4, localId 2
    0x180408, // group 24, map 4, localId 8
    // GraniteCave_B2F
    0x180903, // group 24, map 9, localId 3
    0x180904, // group 24, map 9, localId 4
    0x180905, // group 24, map 9, localId 5
    0x180906, // group 24, map 9, localId 6
    0x180907, // group 24, map 9, localId 7
    0x180908, // group 24, map 9, localId 8
    0x180909, // group 24, map 9, localId 9
    // PetalburgWoods
    0x180B01, // group 24, map 11, localId 1
    0x180B02, // group 24, map 11, localId 2
    // SeafloorCavern_Room1
    0x181C03, // group 24, map 28, localId 3
    // SeafloorCavern_Room2
    0x181D06, // group 24, map 29, localId 6
    0x181D07, // group 24, map 29, localId 7
    // SeafloorCavern_Room5
    0x182004, // group 24, map 32, localId 4
    0x182005, // group 24, map 32, localId 5
    // VictoryRoad_B1F
    0x182C08, // group 24, map 44, localId 8
    0x182C09, // group 24, map 44, localId 9
    0x182C0A, // group 24, map 44, localId 10
    0x182C0B, // group 24, map 44, localId 11
    0x182C0C, // group 24, map 44, localId 12
    0x182C11, // group 24, map 44, localId 17
    // MirageTower_3F
    0x186001, // group 24, map 96, localId 1
    0x186002, // group 24, map 96, localId 2
    // MirageTower_4F
    0x186103, // group 24, map 97, localId 3
    // SafariZone_North
    0x1A0103, // group 26, map 1, localId 3
    0x1A0104, // group 26, map 1, localId 4
    0x1A0105, // group 26, map 1, localId 5
    0x1A0106, // group 26, map 1, localId 6
    0x1A0107, // group 26, map 1, localId 7
    0x1A0108, // group 26, map 1, localId 8
    // SafariZone_Northeast
    0x1A0C03, // group 26, map 12, localId 3
    0x1A0C05, // group 26, map 12, localId 5
    0x1A0C06, // group 26, map 12, localId 6
    0x1A0C07, // group 26, map 12, localId 7
    0x1A0C08, // group 26, map 12, localId 8
    // Route110_TrickHousePuzzle1
    0x1D0304, // group 29, map 3, localId 4
    0x1D0305, // group 29, map 3, localId 5
    0x1D0306, // group 29, map 3, localId 6
    0x1D0307, // group 29, map 3, localId 7
    0x1D0308, // group 29, map 3, localId 8
    0x1D0309, // group 29, map 3, localId 9
    0x1D030A, // group 29, map 3, localId 10
    0x1D030B, // group 29, map 3, localId 11
    0x1D030C, // group 29, map 3, localId 12
    0x1D030E, // group 29, map 3, localId 14
    0x1D030F, // group 29, map 3, localId 15
    // Route110_TrickHousePuzzle3
    0x1D0506, // group 29, map 5, localId 6
    0x1D0507, // group 29, map 5, localId 7
    // CeruleanCave_1F_Frlg
    0x234804, // group 35, map 72, localId 4
    0x234805, // group 35, map 72, localId 5
    0x234806, // group 35, map 72, localId 6
    0x234807, // group 35, map 72, localId 7
    0x234808, // group 35, map 72, localId 8
    0x234809, // group 35, map 72, localId 9
    // CeruleanCave_2F_Frlg
    0x234904, // group 35, map 73, localId 4
    0x234905, // group 35, map 73, localId 5
    0x234906, // group 35, map 73, localId 6
    0x234907, // group 35, map 73, localId 7
    0x234908, // group 35, map 73, localId 8
    0x234909, // group 35, map 73, localId 9
    0x23490A, // group 35, map 73, localId 10
    0x23490B, // group 35, map 73, localId 11
    0x23490C, // group 35, map 73, localId 12
    0x23490D, // group 35, map 73, localId 13
    // CeruleanCave_B1F_Frlg
    0x234A04, // group 35, map 74, localId 4
    0x234A05, // group 35, map 74, localId 5
    0x234A06, // group 35, map 74, localId 6
    0x234A07, // group 35, map 74, localId 7
    0x234A08, // group 35, map 74, localId 8
    0x234A09, // group 35, map 74, localId 9
    0x234A0A, // group 35, map 74, localId 10
    0x234A0B, // group 35, map 74, localId 11
    0x234A0C, // group 35, map 74, localId 12
    // RockTunnel_B1F_Frlg
    0x23520C, // group 35, map 82, localId 12
    0x23520D, // group 35, map 82, localId 13
    0x23520E, // group 35, map 82, localId 14
    0x23520F, // group 35, map 82, localId 15
    0x235210, // group 35, map 82, localId 16
    0x235211, // group 35, map 82, localId 17
    0x235212, // group 35, map 82, localId 18
    0x235213, // group 35, map 82, localId 19
    0x235214, // group 35, map 82, localId 20
    0x235215, // group 35, map 82, localId 21
    0x235216, // group 35, map 82, localId 22
    0x235217, // group 35, map 82, localId 23
    0x235218, // group 35, map 82, localId 24
    0x235219, // group 35, map 82, localId 25
    0x23521A, // group 35, map 82, localId 26
    // MtEmber_Exterior_Frlg
    0x236107, // group 35, map 97, localId 7
    0x236108, // group 35, map 97, localId 8
    0x23610C, // group 35, map 97, localId 12
    0x23610D, // group 35, map 97, localId 13
    0x236110, // group 35, map 97, localId 16
    0x236111, // group 35, map 97, localId 17
    // MtEmber_SummitPath_2F_Frlg
    0x236301, // group 35, map 99, localId 1
    0x236302, // group 35, map 99, localId 2
    0x236303, // group 35, map 99, localId 3
    0x236304, // group 35, map 99, localId 4
    0x236305, // group 35, map 99, localId 5
    0x236306, // group 35, map 99, localId 6
    0x236307, // group 35, map 99, localId 7
    0x236308, // group 35, map 99, localId 8
    0x236309, // group 35, map 99, localId 9
    // MtEmber_RubyPath_1F_Frlg
    0x236701, // group 35, map 103, localId 1
    0x236702, // group 35, map 103, localId 2
    0x236703, // group 35, map 103, localId 3
    0x236704, // group 35, map 103, localId 4
    0x236705, // group 35, map 103, localId 5
    // MtEmber_RubyPath_B1F_Frlg
    0x236801, // group 35, map 104, localId 1
    0x236802, // group 35, map 104, localId 2
    0x236803, // group 35, map 104, localId 3
    0x236804, // group 35, map 104, localId 4
    // MtEmber_RubyPath_B2F_Frlg
    0x236904, // group 35, map 105, localId 4
    0x236905, // group 35, map 105, localId 5
    0x236906, // group 35, map 105, localId 6
    0x236907, // group 35, map 105, localId 7
    // MtEmber_RubyPath_B3F_Frlg
    0x236A04, // group 35, map 106, localId 4
    0x236A05, // group 35, map 106, localId 5
    0x236A06, // group 35, map 106, localId 6
    0x236A07, // group 35, map 106, localId 7
    0x236A08, // group 35, map 106, localId 8
    0x236A09, // group 35, map 106, localId 9
    // MtEmber_RubyPath_B1F_Stairs_Frlg
    0x236B01, // group 35, map 107, localId 1
    // MtEmber_RubyPath_B2F_Stairs_Frlg
    0x236C01, // group 35, map 108, localId 1
    0x236C02, // group 35, map 108, localId 2
    // ThreeIsland_BerryForest_Frlg
    0x236D02, // group 35, map 109, localId 2
    0x236D03, // group 35, map 109, localId 3
    0x236D04, // group 35, map 109, localId 4
    0x236D05, // group 35, map 109, localId 5
    0x236D06, // group 35, map 109, localId 6
    0x236D07, // group 35, map 109, localId 7
    0x236D08, // group 35, map 109, localId 8
    0x236D09, // group 35, map 109, localId 9
    0x236D0A, // group 35, map 109, localId 10
    0x236D0B, // group 35, map 109, localId 11
    // ViridianCity_Frlg
    0x250102, // group 37, map 1, localId 2
    0x250108, // group 37, map 1, localId 8
    // PewterCity_Frlg
    0x250206, // group 37, map 2, localId 6
    // CeruleanCity_Frlg
    0x250309, // group 37, map 3, localId 9
    0x25030A, // group 37, map 3, localId 10
    // VermilionCity_Frlg
    0x250507, // group 37, map 5, localId 7
    // CeladonCity_Frlg
    0x25060A, // group 37, map 6, localId 10
    0x25060B, // group 37, map 6, localId 11
    0x25060D, // group 37, map 6, localId 13
    // FuchsiaCity_Frlg
    0x25070B, // group 37, map 7, localId 11
    0x25070C, // group 37, map 7, localId 12
    0x25070D, // group 37, map 7, localId 13
    0x25070E, // group 37, map 7, localId 14
    // TwoIsland_Frlg
    0x250D06, // group 37, map 13, localId 6
    // ThreeIsland_Frlg
    0x250E09, // group 37, map 14, localId 9
    // FourIsland_Frlg
    0x250F07, // group 37, map 15, localId 7
    // Route2_Frlg
    0x251401, // group 37, map 20, localId 1
    0x251402, // group 37, map 20, localId 2
    0x251403, // group 37, map 20, localId 3
    0x251404, // group 37, map 20, localId 4
    0x251407, // group 37, map 20, localId 7
    // Route8_Frlg
    0x251A0A, // group 37, map 26, localId 10
    0x251A0B, // group 37, map 26, localId 11
    // Route9_Frlg
    0x251B0A, // group 37, map 27, localId 10
    // Route10_Frlg
    0x251C07, // group 37, map 28, localId 7
    0x251C08, // group 37, map 28, localId 8
    0x251C09, // group 37, map 28, localId 9
    0x251C0A, // group 37, map 28, localId 10
    // Route12_Frlg
    0x251E09, // group 37, map 30, localId 9
    0x251E0E, // group 37, map 30, localId 14
    // Route13_Frlg
    0x251F0B, // group 37, map 31, localId 11
    // Route14_Frlg
    0x25200B, // group 37, map 32, localId 11
    0x25200C, // group 37, map 32, localId 12
    0x25200D, // group 37, map 32, localId 13
    // Route15_Frlg
    0x25210E, // group 37, map 33, localId 14
    // Route16_Frlg
    0x252207, // group 37, map 34, localId 7
    // Route25_Frlg
    0x252C0B, // group 37, map 44, localId 11
    // OneIsland_KindleRoad_Frlg
    0x252D0E, // group 37, map 45, localId 14
    0x252D0F, // group 37, map 45, localId 15
    0x252D10, // group 37, map 45, localId 16
    0x252D11, // group 37, map 45, localId 17
    0x252D12, // group 37, map 45, localId 18
    0x252D13, // group 37, map 45, localId 19
    0x252D14, // group 37, map 45, localId 20
    0x252D15, // group 37, map 45, localId 21
    0x252D16, // group 37, map 45, localId 22
    0x252D17, // group 37, map 45, localId 23
    0x252D18, // group 37, map 45, localId 24
    0x252D19, // group 37, map 45, localId 25
    0x252D1A, // group 37, map 45, localId 26
    // ThreeIsland_BondBridge_Frlg
    0x253008, // group 37, map 48, localId 8
    0x253009, // group 37, map 48, localId 9
    // FiveIsland_Meadow_Frlg
    0x253404, // group 37, map 52, localId 4
    0x253405, // group 37, map 52, localId 5
    // SevenIsland_SevaultCanyon_Frlg
    0x253C09, // group 37, map 60, localId 9
    0x253C0B, // group 37, map 60, localId 11
    0x253C0C, // group 37, map 60, localId 12
    0x253C0D, // group 37, map 60, localId 13
    0x253C0E, // group 37, map 60, localId 14
    0x253C10, // group 37, map 60, localId 16
    // CeladonCity_Gym_Frlg
    0x2C1009, // group 44, map 16, localId 9
    0x2C100A, // group 44, map 16, localId 10
    0x2C100B, // group 44, map 16, localId 11
    // Route29
    0x4B0206, // group 75, map 2, localId 6
    // Route30
    0x4B0305, // group 75, map 3, localId 5
    // Route31
    0x4B0407, // group 75, map 4, localId 7
    // Route32
    0x4B0508, // group 75, map 5, localId 8
    0x4B0520, // group 75, map 5, localId 32
    // VioletCity
    0x4B0608, // group 75, map 6, localId 8
    // IlexForest
    0x500304, // group 80, map 3, localId 4
    // Route35
    0x53010A, // group 83, map 1, localId 10
    // NationalPark_Normal
    0x53040B, // group 83, map 4, localId 11
    // Route40
    0x570101, // group 87, map 1, localId 1
    0x570102, // group 87, map 1, localId 2
    0x570103, // group 87, map 1, localId 3
    0x570104, // group 87, map 1, localId 4
    // CianwoodCity
    0x59000F, // group 89, map 0, localId 15
    0x590010, // group 89, map 0, localId 16
    0x590011, // group 89, map 0, localId 17
    0x590012, // group 89, map 0, localId 18
    0x590013, // group 89, map 0, localId 19
    0x590014, // group 89, map 0, localId 20
    // CianwoodGym
    0x5A0009, // group 90, map 0, localId 9
    0x5A000A, // group 90, map 0, localId 10
    // CliffEdgeCave
    0x5A0602, // group 90, map 6, localId 2
    0x5A0603, // group 90, map 6, localId 3
    0x5A0604, // group 90, map 6, localId 4
    0x5A0605, // group 90, map 6, localId 5
    0x5A0606, // group 90, map 6, localId 6
    0x5A0607, // group 90, map 6, localId 7
    0x5A0608, // group 90, map 6, localId 8
    0x5A0609, // group 90, map 6, localId 9
    0x5A060A, // group 90, map 6, localId 10
    0x5A060B, // group 90, map 6, localId 11
    // Route42
    0x5B0103, // group 91, map 1, localId 3
    // IcePath_B4F
    0x5E0B02, // group 94, map 11, localId 2
    0x5E0B03, // group 94, map 11, localId 3
    0x5E0B04, // group 94, map 11, localId 4
    0x5E0B05, // group 94, map 11, localId 5
    0x5E0B06, // group 94, map 11, localId 6
    0x5E0B07, // group 94, map 11, localId 7
    0x5E0B08, // group 94, map 11, localId 8
    0x5E0B09, // group 94, map 11, localId 9
    0x5E0B0A, // group 94, map 11, localId 10
    0x5E0B0B, // group 94, map 11, localId 11
    // DragonsDen_Cavern
    0x5E0C17, // group 94, map 12, localId 23
    0x5E0C18, // group 94, map 12, localId 24
    // DarkCave_NorthSide
    0x5E0F04, // group 94, map 15, localId 4
    0x5E0F05, // group 94, map 15, localId 5
    // DarkCave_SouthSide
    0x5E1002, // group 94, map 16, localId 2
    0x5E1003, // group 94, map 16, localId 3
    0x5E1004, // group 94, map 16, localId 4
    0x5E1005, // group 94, map 16, localId 5
    // MtSilver_2F
    0x610401, // group 97, map 4, localId 1
    0x610402, // group 97, map 4, localId 2
    0x610403, // group 97, map 4, localId 3
    0x610404, // group 97, map 4, localId 4
    0x610405, // group 97, map 4, localId 5
    // TohjoFalls_GiovanniRoom
    0x620902, // group 98, map 9, localId 2
    0x620903, // group 98, map 9, localId 3
    0x620904, // group 98, map 9, localId 4
    0x620905, // group 98, map 9, localId 5
    0x620906, // group 98, map 9, localId 6
    0x620907, // group 98, map 9, localId 7
    0x620908, // group 98, map 9, localId 8
    // JohtoVictoryRoad_B1F
    0x630108, // group 99, map 1, localId 8
    0x630109, // group 99, map 1, localId 9
    0x63010A, // group 99, map 1, localId 10
    0x63010B, // group 99, map 1, localId 11
    0x63010C, // group 99, map 1, localId 12
    0x630111, // group 99, map 1, localId 17
};
